import { CMS_SLICE_11_OPERATION_REASONS } from './refusals.ts';
import type { CmsEditorialRoutePolicy } from './route-policy-contract.ts';
import { tier1Slo, tier2Slo } from './route-slo.ts';
import {
  editorialReviewCommandErrors,
  editorialReviewQueueErrors,
  editorialStepUpCommandErrors,
  editorialWorkflowReadErrors,
} from './routes-errors.ts';

/*
 * BE03b Route Registry rows CMS-03B-05..09 and CMS-03B-15..18: the Slice 11
 * review, schedule, preview, publication, workflow-read, review-detail,
 * reviewer-queue and reviewer-assignment browser operations. CMS-03B-19 and
 * CMS-03B-20 are internal RPCs and have no row (see `internal-rpc.ts`).
 */

/** Members every browser editorial row shares. */
const browserEnvelope = {
  audience: 'browser',
  cors: 'cms-console',
  rawBodySignature: 'none',
  maxBodyBytes: 262_144,
  rateWindowSeconds: 60,
  rateScope: 'user',
  cacheControl: 'no-store',
} as const;

/** A Slice 11 command: CSRF, an idempotency key and an exact strong If-Match. */
const commandGuards = {
  csrf: 'required',
  idempotency: 'required',
  ifMatch: 'required',
} as const;

/** A Slice 11 safe read: no mutation guard, no step-up, no event. */
const readGuards = {
  csrf: 'none',
  idempotency: 'none',
  ifMatch: 'none',
  stepUp: 'none',
  eventType: 'none',
  successStatus: 200,
  outcome: 'read',
  location: 'none',
  etag: 'strong',
  rateClass: 'cms-entry-read',
  rateLimit: 300,
  partyRateLimit: 600,
  timeoutMs: 8_000,
} as const;

/** Every capability that can establish an entry, review or preview scope. */
const scopeCapabilities = [
  'cms.author',
  'cms.editor',
  'cms.reviewer',
  'cms.publisher',
] as const;

export const slice11RoutePolicies = [
  {
    operationId: 'CMS-03B-05',
    method: 'POST',
    path: '/api/v1/cms/entries/{entryId}/reviews',
    requestSchema: 'ReviewSubmissionRequestSchema',
    pathParamsSchema: 'CmsEditorialReviewSubmissionPathParamsSchema',
    headersSchema: 'CmsEditorialReviewSubmissionHeadersSchema',
    successSchema: 'EditorialReviewResourceSchema',
    successStatus: 201,
    outcome: 'created',
    // The strong ETag is `"{review.version}"`; the review is addressable by CMS-03B-16.
    etag: 'strong',
    location: 'required',
    auth: 'editorial_author',
    capabilities: ['cms.author', 'cms.editor'],
    capabilityMode: 'any_of',
    gate: 'capability',
    stepUp: 'none',
    ...browserEnvelope,
    ...commandGuards,
    rateClass: 'cms-review-write',
    rateLimit: 30,
    partyRateLimit: 60,
    timeoutMs: 15_000,
    responseTargetMs: 2_000,
    slo: tier2Slo,
    eventType: 'cms.entry.review-changed.v1',
    reasonCodes: CMS_SLICE_11_OPERATION_REASONS['CMS-03B-05'],
    errors: editorialReviewCommandErrors,
  },
  {
    operationId: 'CMS-03B-06',
    method: 'POST',
    path: '/api/v1/cms/reviews/{reviewId}/decision',
    requestSchema: 'EditorialDecisionRequestSchema',
    pathParamsSchema: 'CmsEditorialDecisionPathParamsSchema',
    headersSchema: 'CmsEditorialDecisionHeadersSchema',
    successSchema: 'EditorialReviewResourceSchema',
    // A decision updates the existing review, so it answers 200 and no Location.
    successStatus: 200,
    outcome: 'updated',
    etag: 'strong',
    location: 'none',
    auth: 'editorial_reviewer',
    capabilities: ['cms.reviewer'],
    capabilityMode: 'any_of',
    gate: 'capability',
    stepUp: 'required',
    ...browserEnvelope,
    ...commandGuards,
    rateClass: 'cms-review-write',
    rateLimit: 30,
    partyRateLimit: 60,
    timeoutMs: 15_000,
    responseTargetMs: 2_000,
    slo: tier2Slo,
    eventType: 'cms.entry.review-changed.v1',
    reasonCodes: CMS_SLICE_11_OPERATION_REASONS['CMS-03B-06'],
    errors: editorialStepUpCommandErrors,
  },
  {
    operationId: 'CMS-03B-07',
    method: 'POST',
    path: '/api/v1/cms/publication-schedules',
    requestSchema: 'PublicationScheduleRequestSchema',
    headersSchema: 'CmsPublicationScheduleHeadersSchema',
    successSchema: 'PublicationScheduleResourceSchema',
    // 202 means scheduled, never published.
    successStatus: 202,
    outcome: 'accepted',
    etag: 'strong',
    location: 'required',
    auth: 'editorial_publisher',
    capabilities: ['cms.publisher'],
    capabilityMode: 'any_of',
    gate: 'capability',
    stepUp: 'required',
    ...browserEnvelope,
    ...commandGuards,
    rateClass: 'cms-schedule-write',
    rateLimit: 20,
    partyRateLimit: 40,
    timeoutMs: 15_000,
    responseTargetMs: 2_000,
    slo: tier2Slo,
    // cms.publication.changed.v1 is emitted only by an executed publication.
    eventType: 'none',
    reasonCodes: CMS_SLICE_11_OPERATION_REASONS['CMS-03B-07'],
    errors: editorialStepUpCommandErrors,
  },
  {
    operationId: 'CMS-03B-08',
    method: 'POST',
    path: '/api/v1/cms/previews',
    requestSchema: 'PreviewRequestSchema',
    headersSchema: 'CmsPreviewRequestHeadersSchema',
    successSchema: 'PreviewTokenResourceSchema',
    successStatus: 201,
    outcome: 'created',
    // The token is derived and never stored: no public ETag and no Location.
    etag: 'none',
    location: 'none',
    auth: 'editorial_preview',
    // Preview scope: entry assignee, active reviewer assignee or owner-party publisher.
    capabilities: scopeCapabilities,
    capabilityMode: 'any_of',
    gate: 'rpc_scope',
    stepUp: 'none',
    ...browserEnvelope,
    ...commandGuards,
    rateClass: 'cms-preview-write',
    rateLimit: 60,
    partyRateLimit: 120,
    timeoutMs: 8_000,
    responseTargetMs: 750,
    slo: tier1Slo,
    eventType: 'none',
    reasonCodes: CMS_SLICE_11_OPERATION_REASONS['CMS-03B-08'],
    errors: editorialReviewCommandErrors,
  },
  {
    operationId: 'CMS-03B-09',
    method: 'POST',
    path: '/api/v1/cms/publications',
    requestSchema: 'PublicationRequestSchema',
    headersSchema: 'CmsPublicationRequestHeadersSchema',
    successSchema: 'PublicationResourceSchema',
    // 202 with projectionState `pending`: committed, not proof of public visibility.
    successStatus: 202,
    outcome: 'accepted',
    etag: 'strong',
    location: 'required',
    auth: 'editorial_publisher',
    capabilities: ['cms.publisher'],
    capabilityMode: 'any_of',
    gate: 'capability',
    stepUp: 'required',
    ...browserEnvelope,
    ...commandGuards,
    rateClass: 'cms-publish-write',
    rateLimit: 20,
    partyRateLimit: 40,
    timeoutMs: 15_000,
    responseTargetMs: 2_000,
    slo: tier2Slo,
    eventType: 'cms.publication.changed.v1',
    reasonCodes: CMS_SLICE_11_OPERATION_REASONS['CMS-03B-09'],
    errors: editorialStepUpCommandErrors,
  },
  {
    operationId: 'CMS-03B-15',
    method: 'GET',
    path: '/api/v1/cms/entries/{entryId}/workflow',
    requestSchema: 'EntryWorkflowQuerySchema',
    pathParamsSchema: 'EntryWorkflowPathParamsSchema',
    querySchema: 'EntryWorkflowQuerySchema',
    successSchema: 'EntryWorkflowResourceSchema',
    ...readGuards,
    auth: 'editorial_workflow_reader',
    capabilities: scopeCapabilities,
    capabilityMode: 'any_of',
    gate: 'rpc_scope',
    ...browserEnvelope,
    // Tier 2 p95 under 1,200ms: the preparation includes the 2,000ms checker budget.
    responseTargetMs: 1_200,
    slo: tier2Slo,
    reasonCodes: CMS_SLICE_11_OPERATION_REASONS['CMS-03B-15'],
    errors: editorialWorkflowReadErrors,
  },
  {
    operationId: 'CMS-03B-16',
    method: 'GET',
    path: '/api/v1/cms/reviews/{reviewId}',
    requestSchema: 'EditorialReviewDetailQuerySchema',
    pathParamsSchema: 'EditorialReviewDetailPathParamsSchema',
    querySchema: 'EditorialReviewDetailQuerySchema',
    successSchema: 'EditorialReviewDetailResourceSchema',
    ...readGuards,
    auth: 'editorial_review_reader',
    capabilities: scopeCapabilities,
    capabilityMode: 'any_of',
    gate: 'rpc_scope',
    ...browserEnvelope,
    responseTargetMs: 750,
    slo: tier1Slo,
    reasonCodes: CMS_SLICE_11_OPERATION_REASONS['CMS-03B-16'],
    errors: editorialWorkflowReadErrors,
  },
  {
    operationId: 'CMS-03B-17',
    method: 'GET',
    path: '/api/v1/cms/reviews',
    requestSchema: 'ReviewQueueQuerySchema',
    querySchema: 'ReviewQueueQuerySchema',
    successSchema: 'ReviewQueuePageSchema',
    ...readGuards,
    // A verified human: the queue is driven from the caller's own assignments or
    // submissions, so no capability gate exists.
    auth: 'editorial_review_queue',
    capabilities: [],
    capabilityMode: 'any_of',
    gate: 'rpc_scope',
    ...browserEnvelope,
    responseTargetMs: 750,
    slo: tier1Slo,
    reasonCodes: CMS_SLICE_11_OPERATION_REASONS['CMS-03B-17'],
    errors: editorialReviewQueueErrors,
  },
  {
    operationId: 'CMS-03B-18',
    method: 'POST',
    path: '/api/v1/cms/reviews/{reviewId}/assignments',
    requestSchema: 'EditorialReviewAssignmentRequestSchema',
    pathParamsSchema: 'EditorialReviewAssignmentPathParamsSchema',
    headersSchema: 'CmsEditorialReviewAssignmentHeadersSchema',
    successSchema: 'EditorialReviewAssignmentResourceSchema',
    // Create answers 201 with a Location; revoke answers 200.
    successStatus: 201,
    additionalSuccessStatuses: [200],
    outcome: 'created',
    etag: 'strong',
    location: 'on_create',
    auth: 'editorial_owner',
    // Owner-only and never grantable: derived from the immutable owner receipt in
    // the RPC, so the Worker applies no coarse capability gate.
    capabilities: ['cms.editorial_review.assign'],
    capabilityMode: 'all_of',
    gate: 'rpc_scope',
    stepUp: 'required',
    ...browserEnvelope,
    ...commandGuards,
    rateClass: 'cms-review-assignment',
    rateLimit: 10,
    partyRateLimit: 20,
    timeoutMs: 15_000,
    responseTargetMs: 2_000,
    slo: tier2Slo,
    eventType: 'cms.entry.review-changed.v1',
    reasonCodes: CMS_SLICE_11_OPERATION_REASONS['CMS-03B-18'],
    errors: editorialStepUpCommandErrors,
  },
] as const satisfies readonly CmsEditorialRoutePolicy[];
