import { assertCmsEditorialRouteRegistry } from './route-policy.ts';
import type { CmsEditorialRoutePolicy } from './route-policy-contract.ts';
import {
  editorialAuthoringContextErrors,
  editorialConflictResolutionErrors,
  editorialConflictDetailErrors,
  editorialDraftDetailErrors,
  editorialEntryCreateErrors,
  editorialEntryListErrors,
  editorialRestoreErrors,
  editorialRevisionErrors,
  editorialRevisionHistoryErrors,
} from './routes-errors.ts';

/** Tier 2 command budget shared by every 03b mutation (p95 under 1,200ms). */
const tier2Slo = {
  tier: 2,
  commandP95Ms: 1_200,
  protectedRpcP95Ms: 300,
  acceptanceP99Ms: 1_000,
} as const;

/** Tier 1 read budget shared by 03b safe reads (p95 under 750ms). */
const tier1Slo = {
  tier: 1,
  commandP95Ms: 750,
  protectedRpcP95Ms: 300,
  acceptanceP99Ms: 1_000,
} as const;

/** The author-or-editor gate shared by every authoring route. */
const authorOrEditor = ['cms.author', 'cms.editor'] as const;

/**
 * CMS-03B-03 additionally grants reviewer read scope, so its capability array
 * is the one authoring gate widened by a third read-only capability.
 */
const authorEditorOrReviewer = [
  'cms.author',
  'cms.editor',
  'cms.reviewer',
] as const;

const routePolicies = [
  {
    operationId: 'CMS-03B-01',
    method: 'POST',
    path: '/api/v1/cms/entries/{entryId}/revisions',
    requestSchema: 'EntryRevisionRequestSchema',
    pathParamsSchema: 'EntryRevisionPathParamsSchema',
    headersSchema: 'EntryRevisionHeadersSchema',
    successSchema: 'EntryRevisionResourceSchema',
    successStatus: 201,
    outcome: 'created',
    etag: 'strong',
    location: 'required',
    auth: 'editorial_author',
    capabilities: authorOrEditor,
    capabilityMode: 'any_of',
    audience: 'browser',
    cors: 'cms-console',
    csrf: 'required',
    rawBodySignature: 'none',
    idempotency: 'required',
    ifMatch: 'required',
    maxBodyBytes: 262_144,
    rateClass: 'cms-entry-write',
    rateLimit: 120,
    partyRateLimit: 240,
    rateWindowSeconds: 60,
    rateScope: 'user',
    timeoutMs: 15_000,
    responseTargetMs: 2_000,
    cacheControl: 'no-store',
    slo: tier2Slo,
    eventType: 'cms.entry.revision-created.v1',
    errors: editorialRevisionErrors,
  },
  {
    operationId: 'CMS-03B-02',
    method: 'POST',
    path: '/api/v1/cms/entries/{entryId}/conflicts/{conflictId}/resolve',
    requestSchema: 'ConflictResolutionRequestSchema',
    pathParamsSchema: 'ConflictResolutionPathParamsSchema',
    headersSchema: 'ConflictResolutionHeadersSchema',
    successSchema: 'EntryRevisionResourceSchema',
    successStatus: 201,
    outcome: 'created',
    // Resolution creates a new two-parent revision and closes the durable open
    // conflict record, so it publishes a Location exactly like a revision save.
    etag: 'strong',
    location: 'required',
    auth: 'editorial_author',
    capabilities: authorOrEditor,
    capabilityMode: 'any_of',
    audience: 'browser',
    cors: 'cms-console',
    csrf: 'required',
    rawBodySignature: 'none',
    // key + If-Match: the command CASes both the conflict base and the entry
    // version, so a stale read can never win a divergent field.
    idempotency: 'required',
    ifMatch: 'required',
    maxBodyBytes: 262_144,
    // BE03b names a distinct "conflict rate class" so conflict resolution never
    // shares a bucket with an ordinary entry write.
    rateClass: 'cms-entry-conflict',
    rateLimit: 60,
    partyRateLimit: 120,
    rateWindowSeconds: 60,
    rateScope: 'user',
    timeoutMs: 15_000,
    responseTargetMs: 2_000,
    cacheControl: 'no-store',
    slo: tier2Slo,
    eventType: 'cms.entry.revision-created.v1',
    errors: editorialConflictResolutionErrors,
  },
  {
    operationId: 'CMS-03B-03',
    method: 'GET',
    path: '/api/v1/cms/entries/{entryId}/revisions',
    requestSchema: 'RevisionHistoryQuerySchema',
    pathParamsSchema: 'RevisionHistoryPathParamsSchema',
    querySchema: 'RevisionHistoryQuerySchema',
    successSchema: 'RevisionHistoryPageSchema',
    successStatus: 200,
    outcome: 'read',
    // BE03b returns an authenticated page ETag over the signed page version;
    // a read never publishes a Location.
    etag: 'strong',
    location: 'none',
    auth: 'editorial_reader',
    capabilities: authorEditorOrReviewer,
    capabilityMode: 'any_of',
    audience: 'browser',
    cors: 'cms-console',
    // A safe read performs no mutation, so CSRF is deliberately absent while
    // the cursor stays context-bound to the actor and acting party.
    csrf: 'none',
    rawBodySignature: 'none',
    idempotency: 'none',
    ifMatch: 'none',
    maxBodyBytes: 262_144,
    rateClass: 'cms-entry-read',
    rateLimit: 300,
    partyRateLimit: 600,
    rateWindowSeconds: 60,
    rateScope: 'user',
    timeoutMs: 8_000,
    responseTargetMs: 750,
    cacheControl: 'no-store',
    slo: tier1Slo,
    eventType: 'none',
    errors: editorialRevisionHistoryErrors,
  },
  {
    operationId: 'CMS-03B-04',
    method: 'POST',
    path: '/api/v1/cms/entries/{entryId}/revisions/{revisionId}/restore',
    requestSchema: 'RevisionRestoreRequestSchema',
    pathParamsSchema: 'RevisionRestorePathParamsSchema',
    headersSchema: 'RevisionRestoreHeadersSchema',
    successSchema: 'EntryRevisionResourceSchema',
    successStatus: 201,
    outcome: 'created',
    // A restore inserts a new draft revision, so it is an ordinary create.
    etag: 'strong',
    location: 'required',
    auth: 'editorial_author',
    capabilities: authorOrEditor,
    capabilityMode: 'any_of',
    audience: 'browser',
    cors: 'cms-console',
    csrf: 'required',
    rawBodySignature: 'none',
    idempotency: 'required',
    ifMatch: 'required',
    maxBodyBytes: 262_144,
    rateClass: 'cms-entry-write',
    rateLimit: 30,
    partyRateLimit: 60,
    rateWindowSeconds: 60,
    rateScope: 'user',
    timeoutMs: 15_000,
    responseTargetMs: 2_000,
    cacheControl: 'no-store',
    slo: tier2Slo,
    eventType: 'cms.entry.revision-created.v1',
    errors: editorialRestoreErrors,
  },
  {
    operationId: 'CMS-03B-10',
    method: 'POST',
    path: '/api/v1/cms/entries',
    requestSchema: 'EntryCreateRequestSchema',
    headersSchema: 'EntryCreateHeadersSchema',
    successSchema: 'EntryCreateResourceSchema',
    successStatus: 201,
    outcome: 'created',
    etag: 'strong',
    location: 'required',
    auth: 'editorial_author',
    capabilities: authorOrEditor,
    capabilityMode: 'any_of',
    audience: 'browser',
    cors: 'cms-console',
    csrf: 'required',
    rawBodySignature: 'none',
    // The single documented mutation exception: Idempotency-Key proves
    // creation, and no prior version exists to match with If-Match.
    idempotency: 'required',
    ifMatch: 'none',
    maxBodyBytes: 262_144,
    rateClass: 'cms-entry-write',
    rateLimit: 120,
    partyRateLimit: 240,
    rateWindowSeconds: 60,
    rateScope: 'user',
    timeoutMs: 15_000,
    responseTargetMs: 2_000,
    cacheControl: 'no-store',
    slo: tier2Slo,
    eventType: 'cms.entry.revision-created.v1',
    errors: editorialEntryCreateErrors,
  },
  {
    operationId: 'CMS-03B-11',
    method: 'GET',
    path: '/api/v1/cms/entries/{entryId}',
    requestSchema: 'EntryDraftDetailQuerySchema',
    pathParamsSchema: 'EntryDraftDetailPathParamsSchema',
    querySchema: 'EntryDraftDetailQuerySchema',
    successSchema: 'EntryDraftDetailResourceSchema',
    successStatus: 200,
    outcome: 'read',
    // A strong no-store ETag on a read is the 03b-11 invariant; it is not a
    // creation ETag and there is no Location to publish.
    etag: 'strong',
    location: 'none',
    auth: 'editorial_reader',
    capabilities: authorOrEditor,
    capabilityMode: 'any_of',
    audience: 'browser',
    cors: 'cms-console',
    csrf: 'none',
    rawBodySignature: 'none',
    idempotency: 'none',
    ifMatch: 'none',
    maxBodyBytes: 262_144,
    rateClass: 'cms-entry-read',
    rateLimit: 300,
    partyRateLimit: 600,
    rateWindowSeconds: 60,
    rateScope: 'user',
    timeoutMs: 8_000,
    responseTargetMs: 750,
    cacheControl: 'no-store',
    slo: tier1Slo,
    eventType: 'none',
    errors: editorialDraftDetailErrors,
  },
  {
    operationId: 'CMS-03B-12',
    method: 'GET',
    path: '/api/v1/cms/entries/{entryId}/conflicts/{conflictId}',
    requestSchema: 'ConflictDetailQuerySchema',
    pathParamsSchema: 'ConflictDetailPathParamsSchema',
    querySchema: 'ConflictDetailQuerySchema',
    successSchema: 'ConflictDetailResourceSchema',
    successStatus: 200,
    outcome: 'read',
    // The strong no-store ETag binds the conflict version plus the entry
    // version; a read never publishes a Location.
    etag: 'strong',
    location: 'none',
    auth: 'editorial_reader',
    capabilities: authorOrEditor,
    capabilityMode: 'any_of',
    audience: 'browser',
    cors: 'cms-console',
    csrf: 'none',
    rawBodySignature: 'none',
    idempotency: 'none',
    ifMatch: 'none',
    maxBodyBytes: 262_144,
    rateClass: 'cms-entry-read',
    rateLimit: 300,
    partyRateLimit: 600,
    rateWindowSeconds: 60,
    rateScope: 'user',
    timeoutMs: 8_000,
    responseTargetMs: 750,
    cacheControl: 'no-store',
    slo: tier1Slo,
    eventType: 'none',
    errors: editorialConflictDetailErrors,
  },
  {
    operationId: 'CMS-03B-13',
    method: 'GET',
    path: '/api/v1/cms/entries',
    requestSchema: 'EntryListQuerySchema',
    querySchema: 'EntryListQuerySchema',
    successSchema: 'EntryListPageSchema',
    successStatus: 200,
    outcome: 'read',
    // The authenticated page ETag binds the signed keyset page version.
    etag: 'strong',
    location: 'none',
    auth: 'editorial_reader',
    capabilities: authorOrEditor,
    capabilityMode: 'any_of',
    audience: 'browser',
    cors: 'cms-console',
    csrf: 'none',
    rawBodySignature: 'none',
    idempotency: 'none',
    ifMatch: 'none',
    maxBodyBytes: 262_144,
    rateClass: 'cms-entry-read',
    rateLimit: 300,
    partyRateLimit: 600,
    rateWindowSeconds: 60,
    rateScope: 'user',
    timeoutMs: 8_000,
    responseTargetMs: 750,
    cacheControl: 'no-store',
    slo: tier1Slo,
    eventType: 'none',
    errors: editorialEntryListErrors,
  },
  {
    operationId: 'CMS-03B-14',
    method: 'GET',
    path: '/api/v1/cms/entries/authoring-context',
    requestSchema: 'AuthoringContextQuerySchema',
    querySchema: 'AuthoringContextQuerySchema',
    successSchema: 'AuthoringContextResourceSchema',
    successStatus: 200,
    outcome: 'read',
    // The preparation read binds the resolved active schema versions and
    // never grants a registry-wide read.
    etag: 'strong',
    location: 'none',
    auth: 'editorial_reader',
    capabilities: authorOrEditor,
    capabilityMode: 'any_of',
    audience: 'browser',
    cors: 'cms-console',
    csrf: 'none',
    rawBodySignature: 'none',
    idempotency: 'none',
    ifMatch: 'none',
    maxBodyBytes: 262_144,
    rateClass: 'cms-entry-read',
    rateLimit: 300,
    partyRateLimit: 600,
    rateWindowSeconds: 60,
    rateScope: 'user',
    timeoutMs: 8_000,
    responseTargetMs: 750,
    cacheControl: 'no-store',
    slo: tier1Slo,
    eventType: 'none',
    errors: editorialAuthoringContextErrors,
  },
] as const satisfies readonly CmsEditorialRoutePolicy[];

export const cmsEditorialRoutePolicies =
  assertCmsEditorialRouteRegistry(routePolicies);
