import {
  adminRoute,
  diagnosticRouteErrors,
  grantRouteErrors,
  inboxRouteErrors,
  mfaResetRouteErrors,
  type AdminWorkspaceRoutePolicy,
} from './admin-route-policy.ts';

export const activeAdminWorkspaceRoutePolicies = [
  adminRoute(
    'CFG-05B-01',
    'GET',
    '/api/v1/admin/inbox',
    'Cfg05b01InboxQuerySchema',
    'Cfg05b01InboxResponseSchema',
    120,
    'admin_inbox_read',
    8_000,
    'none',
    'none',
    inboxRouteErrors,
    true,
  ),
  adminRoute(
    'CFG-05B-04',
    'POST',
    '/api/v1/admin/capability-grants/actions',
    'Cfg05b04CapabilityActionRequestSchema',
    'Cfg05b04CapabilityActionResponseSchema',
    20,
    'admin_capability_write',
    15_000,
    'required',
    'required',
    grantRouteErrors,
    true,
  ),
  adminRoute(
    'CFG-05B-05',
    'POST',
    '/api/v1/admin/audit-diagnostics/actions',
    'Cfg05b05AuditDiagnosticRequestSchema',
    'Cfg05b05AuditDiagnosticResponseSchema',
    30,
    'admin_audit_diagnostic',
    15_000,
    'required',
    'required',
    diagnosticRouteErrors,
    true,
  ),
  {
    // BE05b CFG-05B-06: 5 per hour per user and 10 per hour per party.
    ...adminRoute(
      'CFG-05B-06',
      'POST',
      '/api/v1/admin/identity/mfa-factor-resets',
      'Cfg05b06MfaFactorResetRequestSchema',
      'Cfg05b06MfaFactorResetResponseSchema',
      5,
      'admin_mfa_factor_reset',
      15_000,
      'required',
      'none',
      mfaResetRouteErrors,
      true,
    ),
    stepUp: 'required',
    capability: 'admin.identity.mfa_reset',
    partyRateLimit: 10,
    rateWindowSeconds: 3600,
  },
] as const satisfies readonly AdminWorkspaceRoutePolicy[];
