import { createRegistrySet } from './registries.ts';

const routeDefaults = {
  authClass: 'public',
  cacheClass: 'no_store',
  timeoutMs: 8_000,
  rateClass: 'public_read',
  sloTier: 'tier_1',
  criticality: 'high',
  owner: 'Infrastructure',
  requestSchema: 'EmptyRequestSchema',
  errorSchemas: ['ApiErrorSchema'],
  bolaTest: 'no object selector is accepted',
  runbook: 'docs/runbooks/platform/operational-endpoints.md',
  deprecated: false,
} as const;

const authRouteDefaults = {
  ...routeDefaults,
  owner: 'Identity',
  rateClass: 'authentication',
  runbook: 'docs/runbooks/platform/request-security-and-interaction.md',
} as const;

const identityRouteDefaults = {
  ...routeDefaults,
  authClass: 'authenticated',
  owner: 'Identity',
  rateClass: 'identity_command',
  sloTier: 'tier_2',
  runbook: 'docs/runbooks/platform/request-security-and-interaction.md',
} as const;

const identityReadRouteDefaults = {
  ...identityRouteDefaults,
  timeoutMs: 8_000,
  rateClass: 'authenticated_read',
  sloTier: 'tier_1',
} as const;

const identityStepUpRouteDefaults = {
  ...identityRouteDefaults,
  authClass: 'authenticated_step_up',
} as const;

const identityStepUpReadRouteDefaults = {
  ...identityStepUpRouteDefaults,
  rateClass: 'identity_legal_read',
  sloTier: 'tier_1',
} as const;

const identityPublicRouteDefaults = {
  ...routeDefaults,
  owner: 'Identity',
  rateClass: 'public_read',
  cacheClass: 'public_60s',
  runbook: 'docs/runbooks/platform/request-security-and-interaction.md',
} as const;

const profileRouteDefaults = {
  ...routeDefaults,
  authClass: 'authenticated',
  owner: 'Profiles',
  rateClass: 'profile_command',
  sloTier: 'tier_2',
  runbook: 'docs/runbooks/platform/request-security-and-interaction.md',
} as const;

const profileReadRouteDefaults = {
  ...profileRouteDefaults,
  timeoutMs: 8_000,
  rateClass: 'profile_read',
  sloTier: 'tier_1',
} as const;

const profileStepUpRouteDefaults = {
  ...profileRouteDefaults,
  authClass: 'authenticated_step_up',
} as const;

const profilePublicRouteDefaults = {
  ...routeDefaults,
  owner: 'Profiles',
  rateClass: 'profile_remedy',
  sloTier: 'tier_2',
  runbook: 'docs/runbooks/platform/request-security-and-interaction.md',
} as const;

const contentSchemaRegistryRouteDefaults = {
  ...routeDefaults,
  cacheClass: 'no_store',
  cacheControl: 'no-store',
  timeoutMs: 15_000,
  sloTier: 'tier_2',
  criticality: 'high',
  owner: 'ContentSchema',
  errorSchemas: ['ApiErrorSchema'],
  runbook: 'docs/runbooks/platform/operational-endpoints.md',
  deprecated: false,
  slo: {
    tier: 2,
    commandP95Ms: 1_200,
    protectedRpcP95Ms: 300,
    acceptanceP99Ms: 1_000,
  },
} as const;

const editorialRouteDefaults = {
  ...routeDefaults,
  cacheClass: 'no_store',
  cacheControl: 'no-store',
  criticality: 'high',
  owner: 'Editorial',
  errorSchemas: ['ApiErrorSchema'],
  runbook: 'docs/runbooks/platform/operational-endpoints.md',
} as const;

export const platformRegistrySet = createRegistrySet({
  routes: [
    {
      ...routeDefaults,
      method: 'GET',
      path: '/api/v1/health',
      operationId: 'healthRead',
      successSchema: 'HealthResponseSchema',
    },
    {
      ...routeDefaults,
      method: 'GET',
      path: '/api/v1/ready',
      operationId: 'readinessRead',
      successSchema: 'ReadinessResponseSchema',
    },
    {
      ...routeDefaults,
      method: 'GET',
      path: '/api/v1/internal/diagnostics',
      authClass: 'operator_step_up',
      operationId: 'diagnosticsRead',
      successSchema: 'DiagnosticResponseSchema',
    },
    {
      ...routeDefaults,
      method: 'GET',
      path: '/api/v1/jobs/{jobId}',
      authClass: 'authenticated',
      rateClass: 'authenticated_read',
      operationId: 'jobStatusRead',
      requestSchema: 'JobIdPathSchema',
      successSchema: 'JobStatusSchema',
      bolaTest:
        'owner, acting-party jobs.read, or operator jobs.read:any with step-up and reason',
      runbook: 'docs/runbooks/platform/jobs-outbox-reconciliation.md',
    },
    {
      ...routeDefaults,
      method: 'POST',
      path: '/api/v1/upload-intents',
      authClass: 'authenticated',
      rateClass: 'upload_admission',
      timeoutMs: 15_000,
      operationId: 'uploadIntentCreate',
      requestSchema: 'UploadAdmissionRequestSchema',
      successSchema: 'UploadIntentResourceSchema',
      bolaTest:
        'server-resolved actor and acting party must retain target upload authority',
      runbook: 'docs/runbooks/platform/upload-admission-reconciliation.md',
    },
    {
      ...authRouteDefaults,
      method: 'GET',
      path: '/api/v1/auth/providers',
      operationId: 'authProviderCatalogRead',
      cacheClass: 'public_60s',
      successSchema: 'ProviderCatalogSchema',
    },
    {
      ...authRouteDefaults,
      method: 'POST',
      path: '/api/v1/auth/email/start',
      operationId: 'authEmailStart',
      requestSchema: 'EmailStartRequestSchema',
      successSchema: 'AuthStartAcceptedSchema',
    },
    {
      ...authRouteDefaults,
      method: 'POST',
      path: '/api/v1/auth/oauth/start',
      operationId: 'authOAuthStart',
      stepUp: 'conditional',
      requestSchema: 'OAuthStartRequestSchema',
      successSchema: 'AuthorizationStartSchema',
    },
    {
      ...authRouteDefaults,
      method: 'GET',
      path: '/auth/callback',
      operationId: 'authCallbackComplete',
      authClass: 'callback_state',
      requestSchema: 'AuthCallbackApiRequestSchema',
      successSchema: 'AuthEmptyBodySchema',
    },
    {
      ...authRouteDefaults,
      method: 'GET',
      path: '/api/v1/account/login-methods',
      operationId: 'authLoginMethodsRead',
      authClass: 'authenticated',
      rateClass: 'authenticated_read',
      successSchema: 'LoginMethodsResourceSchema',
      bolaTest: 'server-derived current person can read only its login methods',
    },
    {
      ...authRouteDefaults,
      method: 'POST',
      path: '/api/v1/account/login-methods/{provider}/link-intents',
      operationId: 'authLoginMethodLinkIntentCreate',
      stepUp: 'required',
      authClass: 'authenticated_step_up',
      timeoutMs: 15_000,
      requestSchema: 'LinkIntentApiRequestSchema',
      successSchema: 'AuthorizationStartSchema',
      bolaTest: 'provider link intent is bound to the current self session',
    },
    {
      ...authRouteDefaults,
      method: 'DELETE',
      path: '/api/v1/account/login-methods/{identityId}',
      operationId: 'authLoginMethodUnlink',
      stepUp: 'required',
      authClass: 'authenticated_step_up',
      timeoutMs: 15_000,
      requestSchema: 'UnlinkApiRequestSchema',
      successSchema: 'LoginMethodsResourceSchema',
      bolaTest:
        'identity method ownership is concealed from every other person',
    },
    {
      ...authRouteDefaults,
      method: 'POST',
      path: '/api/v1/account-merges',
      operationId: 'authAccountMergeCreate',
      stepUp: 'required',
      authClass: 'authenticated_step_up',
      timeoutMs: 15_000,
      requestSchema: 'MergeCreateApiRequestSchema',
      successSchema: 'MergeCaseResourceSchema',
      bolaTest: 'merge survivor is always the current server-derived person',
    },
    {
      ...authRouteDefaults,
      method: 'GET',
      path: '/api/v1/account-merges/{mergeId}',
      operationId: 'authAccountMergeRead',
      authClass: 'authenticated',
      rateClass: 'authenticated_read',
      requestSchema: 'AuthMergePathSchema',
      successSchema: 'MergeCaseResourceSchema',
      bolaTest: 'non-survivor merge identifiers are concealed as absent',
    },
    {
      ...authRouteDefaults,
      method: 'POST',
      path: '/api/v1/account-merges/{mergeId}/prove-duplicate',
      operationId: 'authAccountMergeProofCreate',
      stepUp: 'required',
      authClass: 'authenticated_step_up',
      timeoutMs: 15_000,
      requestSchema: 'MergeProofApiRequestSchema',
      successSchema: 'AuthorizationStartSchema',
      bolaTest: 'only the survivor can prove a distinct duplicate identity',
    },
    {
      ...authRouteDefaults,
      method: 'POST',
      path: '/api/v1/account-merges/{mergeId}/confirm',
      operationId: 'authAccountMergeConfirm',
      stepUp: 'required',
      authClass: 'authenticated_step_up',
      timeoutMs: 15_000,
      requestSchema: 'MergeConfirmApiRequestSchema',
      successSchema: 'JobStatusSchema',
      bolaTest:
        'only the survivor can confirm the current conflict plan version',
    },
    {
      ...authRouteDefaults,
      method: 'GET',
      path: '/api/v1/auth/session',
      operationId: 'authSessionRead',
      authClass: 'authenticated',
      rateClass: 'authenticated_read',
      successSchema: 'SessionResourceSchema',
    },
    {
      ...authRouteDefaults,
      method: 'POST',
      path: '/api/v1/auth/session/refresh',
      operationId: 'authSessionRefresh',
      authClass: 'authenticated',
      requestSchema: 'SessionRefreshApiRequestSchema',
      successSchema: 'SessionResourceSchema',
    },
    {
      ...authRouteDefaults,
      method: 'POST',
      path: '/api/v1/auth/bootstrap',
      operationId: 'authPersonBootstrap',
      authClass: 'authenticated',
      timeoutMs: 15_000,
      requestSchema: 'PersonBootstrapApiRequestSchema',
      successSchema: 'PersonBootstrapResourceSchema',
    },
    {
      ...authRouteDefaults,
      method: 'POST',
      path: '/api/v1/auth/logout',
      operationId: 'authLogout',
      stepUp: 'conditional',
      authClass: 'authenticated',
      timeoutMs: 15_000,
      requestSchema: 'LogoutApiRequestSchema',
      successSchema: 'AuthEmptyBodySchema',
    },
    {
      ...authRouteDefaults,
      method: 'GET',
      path: '/api/v1/account/mfa/factors',
      operationId: 'authMfaFactorsRead',
      stepUp: 'none',
      authClass: 'authenticated',
      rateClass: 'authenticated_read',
      successSchema: 'MfaFactorsResourceSchema',
      bolaTest: 'server-derived current person can read only its MFA factors',
    },
    {
      ...authRouteDefaults,
      method: 'POST',
      path: '/api/v1/account/mfa/factors',
      operationId: 'authMfaEnrollmentStart',
      stepUp: 'conditional',
      authClass: 'authenticated_step_up_conditional',
      sloTier: 'tier_2',
      timeoutMs: 15_000,
      requestSchema: 'TotpEnrollmentStartApiRequestSchema',
      successSchema: 'TotpEnrollmentStartSchema',
      bolaTest: 'enrollment is bound to the current self account only',
    },
    {
      ...authRouteDefaults,
      method: 'POST',
      path: '/api/v1/account/mfa/factors/{factorId}/verify',
      operationId: 'authMfaFactorVerify',
      stepUp: 'none',
      authClass: 'authenticated',
      sloTier: 'tier_2',
      timeoutMs: 15_000,
      requestSchema: 'MfaFactorVerifyApiRequestSchema',
      successSchema: 'MfaFactorsResourceSchema',
      bolaTest: 'factor ownership is concealed from every other person',
    },
    {
      ...authRouteDefaults,
      method: 'DELETE',
      path: '/api/v1/account/mfa/factors/{factorId}',
      operationId: 'authMfaFactorRemove',
      stepUp: 'conditional',
      authClass: 'authenticated_step_up_conditional',
      sloTier: 'tier_2',
      timeoutMs: 15_000,
      requestSchema: 'MfaFactorRemoveApiRequestSchema',
      successSchema: 'MfaFactorsResourceSchema',
      bolaTest: 'factor ownership is concealed from every other person',
    },
    {
      ...authRouteDefaults,
      method: 'POST',
      path: '/api/v1/auth/step-up/challenges',
      operationId: 'authStepUpChallengeCreate',
      stepUp: 'none',
      authClass: 'authenticated',
      sloTier: 'tier_2',
      requestSchema: 'StepUpChallengeApiRequestSchema',
      successSchema: 'StepUpChallengeSchema',
      bolaTest: 'challenge is bound to the current Auth user and session',
    },
    {
      ...authRouteDefaults,
      method: 'POST',
      path: '/api/v1/auth/step-up/challenges/{challengeId}/verify',
      operationId: 'authStepUpVerify',
      stepUp: 'none',
      authClass: 'authenticated',
      sloTier: 'tier_2',
      requestSchema: 'StepUpVerifyApiRequestSchema',
      successSchema: 'StepUpResultSchema',
      bolaTest:
        'challenge is concealed unless it belongs to the same Auth user and session',
    },
    {
      ...routeDefaults,
      method: 'POST',
      path: '/api/v1/upload-intents/{uploadIntentId}/complete',
      authClass: 'authenticated',
      rateClass: 'upload_admission',
      timeoutMs: 15_000,
      operationId: 'uploadIntentComplete',
      requestSchema: 'UploadCompletionRequestSchema',
      successSchema: 'JobStatusSchema',
      bolaTest:
        'same actor and acting party must own the live intent and retain current target authority',
      runbook: 'docs/runbooks/platform/upload-admission-reconciliation.md',
    },
    {
      ...identityRouteDefaults,
      method: 'POST',
      path: '/api/v1/me/identity',
      timeoutMs: 15_000,
      rateClass: 'identity_provisioning',
      operationId: 'identityCreate',
      requestSchema: 'CreatePersonApiRequestSchema',
      successSchema: 'PersonIdentityResponseSchema',
      bolaTest:
        'verified human with no active PersonParty for resolved Auth subject',
    },
    {
      ...identityReadRouteDefaults,
      method: 'GET',
      path: '/api/v1/me/identity',
      operationId: 'identityReadSelf',
      requestSchema: 'ReadPersonApiRequestSchema',
      successSchema: 'PersonIdentityResponseSchema',
      bolaTest: 'authenticated human resolves exactly one own person',
    },
    {
      ...identityRouteDefaults,
      method: 'POST',
      path: '/api/v1/me/facets',
      timeoutMs: 15_000,
      rateClass: 'identity_facet_mutation',
      operationId: 'identityFacetAdd',
      requestSchema: 'AddFacetApiRequestSchema',
      successSchema: 'FacetMutationResponseSchema',
      bolaTest: 'acting human is subject PersonParty',
    },
    {
      ...identityRouteDefaults,
      method: 'DELETE',
      path: '/api/v1/me/facets/{facetCode}',
      timeoutMs: 15_000,
      rateClass: 'identity_facet_mutation',
      operationId: 'identityFacetRemove',
      requestSchema: 'RemoveFacetApiRequestSchema',
      successSchema: 'FacetMutationResponseSchema',
      bolaTest: 'acting human is subject and facet is active',
    },
    {
      ...identityRouteDefaults,
      method: 'POST',
      path: '/api/v1/aliases',
      timeoutMs: 15_000,
      rateClass: 'identity_alias_create',
      operationId: 'identityAliasCreate',
      requestSchema: 'CreateAliasApiRequestSchema',
      successSchema: 'AliasResponseSchema',
      bolaTest: 'active person owns new alias at creation',
    },
    {
      ...identityRouteDefaults,
      method: 'PATCH',
      path: '/api/v1/aliases/{aliasId}',
      timeoutMs: 15_000,
      rateClass: 'identity_alias_mutation',
      operationId: 'identityAliasPatch',
      requestSchema: 'PatchAliasApiRequestSchema',
      successSchema: 'AliasResponseSchema',
      bolaTest:
        'current owner of open period; alias context alone is insufficient for ownership change',
    },
    {
      ...identityRouteDefaults,
      method: 'POST',
      path: '/api/v1/aliases/{aliasId}/handle-changes',
      timeoutMs: 15_000,
      rateClass: 'identity_handle_change',
      operationId: 'identityHandleChange',
      requestSchema: 'ChangeHandleApiRequestSchema',
      successSchema: 'AliasResponseSchema',
      bolaTest: 'current owner; alias must not be retired or transfer-pending',
    },
    {
      ...identityRouteDefaults,
      method: 'POST',
      path: '/api/v1/aliases/{aliasId}/retire',
      timeoutMs: 15_000,
      rateClass: 'identity_alias_mutation',
      operationId: 'identityAliasRetire',
      requestSchema: 'RetireAliasApiRequestSchema',
      successSchema: 'AliasResponseSchema',
      bolaTest: 'current owner with no forbidden open obligation',
    },
    {
      ...identityRouteDefaults,
      method: 'POST',
      path: '/api/v1/aliases/{aliasId}/transfer-offers',
      timeoutMs: 15_000,
      rateClass: 'identity_transfer',
      operationId: 'identityTransferOfferCreate',
      requestSchema: 'CreateTransferOfferApiRequestSchema',
      successSchema: 'TransferOfferResponseSchema',
      bolaTest: 'current owner; recipient is another active person',
    },
    {
      ...identityRouteDefaults,
      method: 'POST',
      path: '/api/v1/alias-transfer-offers/{offerId}/accept',
      timeoutMs: 15_000,
      rateClass: 'identity_transfer',
      operationId: 'identityTransferAccept',
      requestSchema: 'TransferDecisionApiRequestSchema',
      successSchema: 'AliasResponseSchema',
      bolaTest:
        'authenticated recipient person named by offer; both people remain active',
    },
    {
      ...identityRouteDefaults,
      method: 'POST',
      path: '/api/v1/alias-transfer-offers/{offerId}/decline',
      timeoutMs: 15_000,
      rateClass: 'identity_transfer',
      operationId: 'identityTransferDecline',
      requestSchema: 'TransferDecisionApiRequestSchema',
      successSchema: 'TransferOfferResponseSchema',
      bolaTest:
        'authenticated recipient or offering owner may decline before acceptance',
    },
    {
      ...identityReadRouteDefaults,
      method: 'GET',
      path: '/api/v1/me/acting-contexts',
      operationId: 'identityContextsRead',
      requestSchema: 'ReadActingContextsApiRequestSchema',
      successSchema: 'ActingContextListResponseSchema',
      bolaTest: 'authenticated human; candidates derived from current records',
    },
    {
      ...identityRouteDefaults,
      method: 'POST',
      path: '/api/v1/me/acting-context-bindings',
      timeoutMs: 15_000,
      rateClass: 'identity_context_mutation',
      operationId: 'identityContextBind',
      requestSchema: 'BindContextApiRequestSchema',
      successSchema: 'ActingContextBindingResponseSchema',
      bolaTest:
        'authenticated human currently holds target self/alias/accepted 01c relationship',
    },
    {
      ...identityStepUpReadRouteDefaults,
      method: 'GET',
      path: '/api/v1/me/legal-identity',
      operationId: 'identityLegalRead',
      requestSchema: 'EmptyRequestSchema',
      successSchema: 'LegalIdentityMetadataResponseSchema',
      bolaTest: 'subject person only; recent step-up for protected metadata',
    },
    {
      ...identityStepUpRouteDefaults,
      method: 'PUT',
      path: '/api/v1/me/legal-identity',
      timeoutMs: 15_000,
      rateClass: 'identity_legal_mutation',
      operationId: 'identityLegalUpsert',
      requestSchema: 'PutLegalIdentityApiRequestSchema',
      successSchema: 'LegalIdentityMetadataResponseSchema',
      bolaTest: 'subject person only; recent step-up; effective period valid',
    },
    {
      ...identityStepUpRouteDefaults,
      method: 'POST',
      path: '/api/v1/legal-identity-disclosures',
      timeoutMs: 15_000,
      rateClass: 'identity_legal_disclosure',
      operationId: 'identityLegalDisclose',
      requestSchema: 'CreateDisclosureApiRequestSchema',
      successSchema: 'DisclosureEventResponseSchema',
      bolaTest:
        'human actor, acting context must be person (never alias), eligible transaction and recipient/purpose allowlist',
    },
    {
      ...identityStepUpReadRouteDefaults,
      method: 'GET',
      path: '/api/v1/legal-identity-disclosures/{disclosureId}',
      operationId: 'identityDisclosureRead',
      requestSchema: 'LegalDisclosurePathSchema',
      successSchema: 'DisclosureEventResponseSchema',
      bolaTest:
        'event actor, recipient, subject person, or scoped counsel/operator; no alias linkage disclosure',
    },
    {
      ...identityPublicRouteDefaults,
      method: 'GET',
      path: '/api/v1/identity/parties/{partyId}/projection',
      operationId: 'identityPublicProjection',
      requestSchema: 'ReadPublicProjectionApiRequestSchema',
      successSchema: 'PublicPartyProjectionResponseSchema',
      bolaTest:
        'anonymous or authenticated viewer receives publication-approved projection only',
    },
    {
      ...identityRouteDefaults,
      method: 'POST',
      path: '/api/v1/organizations',
      timeoutMs: 15_000,
      operationId: 'organizationCreate',
      requestSchema: 'CreateOrganizationApiRequestSchema',
      successSchema: 'OrganizationResourceSchema',
      bolaTest: 'verified human creates only its server-derived organization',
    },
    {
      ...identityPublicRouteDefaults,
      method: 'GET',
      path: '/api/v1/organizations/{organizationId}',
      operationId: 'organizationRead',
      requestSchema: 'ReadOrganizationApiRequestSchema',
      successSchema: 'OrganizationReadResponseSchema',
      bolaTest:
        'anonymous receives public projection; authorized context may receive detail',
    },
    {
      ...identityRouteDefaults,
      method: 'POST',
      path: '/api/v1/organizations/{organizationId}/type-assignments',
      timeoutMs: 15_000,
      operationId: 'organizationTypeAdd',
      requestSchema: 'AddOrganizationTypeApiRequestSchema',
      successSchema: 'OrganizationTypeAssignmentResourceSchema',
      bolaTest: 'current organization owner or admin controls type assignment',
    },
    {
      ...identityRouteDefaults,
      method: 'DELETE',
      path: '/api/v1/organizations/{organizationId}/type-assignments/{assignmentId}',
      timeoutMs: 15_000,
      operationId: 'organizationTypeRemove',
      requestSchema: 'RemoveOrganizationTypeApiRequestSchema',
      successSchema: 'OrganizationResourceSchema',
      bolaTest: 'current owner or admin removes only its active assignment',
    },
    {
      ...identityRouteDefaults,
      method: 'POST',
      path: '/api/v1/organizations/{organizationId}/membership-invitations',
      timeoutMs: 15_000,
      operationId: 'membershipInvite',
      requestSchema: 'InviteMembershipApiRequestSchema',
      successSchema: 'MembershipTenureResourceSchema',
      bolaTest: 'capable organization actor invites an existing target person',
    },
    {
      ...identityRouteDefaults,
      method: 'POST',
      path: '/api/v1/organizations/{organizationId}/membership-assertions',
      timeoutMs: 15_000,
      operationId: 'membershipAssert',
      requestSchema: 'AssertHistoricalMembershipApiRequestSchema',
      successSchema: 'MembershipTenureResourceSchema',
      bolaTest: 'owner or self actor asserts history with protected evidence',
    },
    {
      ...identityRouteDefaults,
      method: 'POST',
      path: '/api/v1/membership-tenures/{tenureId}/accept',
      timeoutMs: 15_000,
      operationId: 'membershipAccept',
      requestSchema: 'AcceptMembershipApiRequestSchema',
      successSchema: 'MembershipTenureResourceSchema',
      bolaTest: 'only the invited person accepts its current tenure terms',
    },
    {
      ...identityRouteDefaults,
      method: 'POST',
      path: '/api/v1/membership-tenures/{tenureId}/end',
      timeoutMs: 15_000,
      rateClass: 'identity_relationship_high_risk',
      operationId: 'membershipEnd',
      requestSchema: 'EndMembershipApiRequestSchema',
      successSchema: 'MembershipTenureResourceSchema',
      bolaTest: 'current confirmed counterparty ends only its tenure',
    },
    {
      ...identityRouteDefaults,
      method: 'POST',
      path: '/api/v1/membership-tenures/{tenureId}/capacity-periods',
      timeoutMs: 15_000,
      operationId: 'membershipCapacityAdd',
      requestSchema: 'AddCapacityPeriodApiRequestSchema',
      successSchema: 'MembershipCapacityPeriodResourceSchema',
      bolaTest:
        'authorized organization or current subject adds contained capacity',
    },
    {
      ...identityReadRouteDefaults,
      method: 'GET',
      path: '/api/v1/organizations/{organizationId}/memberships',
      operationId: 'membershipsRead',
      requestSchema: 'ReadMembershipsApiRequestSchema',
      successSchema: 'MembershipCollectionSchema',
      bolaTest:
        'member, organization admin, or named operator reads scoped roster',
    },
    {
      ...profileRouteDefaults,
      method: 'POST',
      path: '/api/v1/shadow-party-matches',
      timeoutMs: 8_000,
      rateClass: 'profile_match',
      operationId: 'profileMatchCreate',
      requestSchema: 'MatchApiRequestSchema',
      successSchema: 'MatchResponseSchema',
      bolaTest: 'verified actor may match only its own source reference',
    },
    {
      ...profileRouteDefaults,
      method: 'POST',
      path: '/api/v1/shadow-parties/{shadowId}/invitations',
      rateClass: 'profile_invitation',
      operationId: 'profileInvitationCreate',
      requestSchema: 'InvitationApiRequestSchema',
      successSchema: 'JobStatusSchema',
      bolaTest: 'verified creator may invite only its own shadow party',
    },
    {
      ...profilePublicRouteDefaults,
      method: 'POST',
      path: '/api/v1/shadow-remedies',
      operationId: 'profileRemedyCreate',
      requestSchema: 'RemedyApiRequestSchema',
      successSchema: 'RemedyResourceSchema',
      bolaTest: 'proof-bound pointer cannot disclose another claim',
    },
    {
      ...profileRouteDefaults,
      method: 'POST',
      path: '/api/v1/party-claims',
      operationId: 'profileClaimCreate',
      rateClass: 'profile_claim',
      requestSchema: 'ClaimCreateApiRequestSchema',
      successSchema: 'ClaimResourceSchema',
      bolaTest: 'server-derived claimant may target only an eligible party',
    },
    {
      ...profileReadRouteDefaults,
      method: 'GET',
      path: '/api/v1/party-claims/{claimId}',
      operationId: 'profileClaimRead',
      rateClass: 'profile_claim_read',
      requestSchema: 'ClaimPathSchema',
      successSchema: 'ClaimResourceSchema',
      bolaTest: 'claim participant receives only its authorized projection',
    },
    {
      ...profileRouteDefaults,
      method: 'POST',
      path: '/api/v1/party-claims/{claimId}/challenges',
      operationId: 'profileChallengeCreate',
      rateClass: 'profile_challenge',
      requestSchema: 'ChallengeApiRequestSchema',
      successSchema: 'ChallengeResourceSchema',
      bolaTest: 'claim participant may issue only its bound challenge',
    },
    {
      ...profileStepUpRouteDefaults,
      method: 'POST',
      path: '/api/v1/party-claims/{claimId}/proofs',
      operationId: 'profileProofCreate',
      rateClass: 'profile_proof',
      requestSchema: 'ProofApiRequestSchema',
      successSchema: 'ClaimResourceSchema',
      bolaTest: 'step-up claimant or eligible attester proves this claim only',
    },
    {
      ...profileStepUpRouteDefaults,
      method: 'POST',
      path: '/api/v1/party-claims/{claimId}/convert',
      operationId: 'profileConversionCreate',
      rateClass: 'profile_conversion',
      requestSchema: 'ConversionApiRequestSchema',
      successSchema: 'ClaimResourceSchema',
      bolaTest: 'step-up owner converts only its current claim version',
    },
    {
      ...contentSchemaRegistryRouteDefaults,
      method: 'POST',
      path: '/api/v1/cms/content-types',
      operationId: 'CMS-03A-01',
      stepUp: 'none',
      authClass: 'schema_designer',
      capability: 'cms.schema_designer',
      capabilities: ['cms.schema_designer'],
      corsClass: 'cms-console',
      audience: 'browser',
      csrf: 'required',
      rawBodySignature: 'none',
      idempotency: 'required',
      ifMatch: 'none',
      rateClass: 'cms-definition-write',
      rateLimit: 30,
      partyRateLimit: 60,
      rateWindowSeconds: 60,
      rateScope: 'user',
      requestSchema: 'ContentTypeDraftRequestSchema',
      successSchema: 'ContentTypeVersionResourceSchema',
      bolaTest: 'caller scope owns the new content type key',
    },
    {
      ...contentSchemaRegistryRouteDefaults,
      method: 'POST',
      path: '/api/v1/cms/content-types/{contentTypeId}/versions/{versionId}/fields',
      operationId: 'CMS-03A-02',
      stepUp: 'none',
      authClass: 'schema_designer',
      capability: 'cms.schema_designer',
      capabilities: ['cms.schema_designer'],
      corsClass: 'cms-console',
      audience: 'browser',
      csrf: 'required',
      rawBodySignature: 'none',
      idempotency: 'required',
      ifMatch: 'required',
      rateClass: 'cms-definition-write',
      rateLimit: 60,
      partyRateLimit: 120,
      rateWindowSeconds: 60,
      rateScope: 'user',
      requestSchema: 'FieldSchemaChangeRequestSchema',
      successSchema: 'FieldDefinitionVersionResourceSchema',
      bolaTest: 'caller scope owns the draft content type version',
    },
    {
      ...contentSchemaRegistryRouteDefaults,
      method: 'POST',
      path: '/api/v1/cms/content-types/{contentTypeId}/versions/{versionId}/relations',
      operationId: 'CMS-03A-03',
      stepUp: 'none',
      authClass: 'schema_designer',
      capability: 'cms.schema_designer',
      capabilities: ['cms.schema_designer'],
      corsClass: 'cms-console',
      audience: 'browser',
      csrf: 'required',
      rawBodySignature: 'none',
      idempotency: 'required',
      ifMatch: 'required',
      rateClass: 'cms-definition-write',
      rateLimit: 60,
      partyRateLimit: 120,
      rateWindowSeconds: 60,
      rateScope: 'user',
      requestSchema: 'RelationBindingRequestSchema',
      successSchema: 'RelationDefinitionResourceSchema',
      bolaTest: 'caller scope owns the draft relation target',
    },
    {
      ...contentSchemaRegistryRouteDefaults,
      method: 'POST',
      path: '/api/v1/cms/content-types/{contentTypeId}/versions/{versionId}/activate',
      operationId: 'CMS-03A-04',
      authClass: 'schema_designer',
      capability: 'cms.schema_designer',
      capabilities: ['cms.schema_designer'],
      corsClass: 'cms-console',
      audience: 'browser',
      csrf: 'required',
      stepUp: 'required',
      rawBodySignature: 'none',
      idempotency: 'required',
      ifMatch: 'required',
      rateClass: 'cms-activation',
      rateLimit: 10,
      partyRateLimit: 20,
      rateWindowSeconds: 60,
      rateScope: 'user',
      requestSchema: 'SchemaActivationRequestSchema',
      successSchema: 'SchemaActivationResourceSchema',
      criticality: 'critical',
      bolaTest: 'distinct approved authority owns the candidate activation',
    },
    {
      ...contentSchemaRegistryRouteDefaults,
      method: 'POST',
      path: '/api/v1/cms/blocks/versions',
      operationId: 'CMS-03A-05',
      stepUp: 'none',
      authClass: 'signed_release_worker',
      capability: 'release.block_registry.write',
      capabilities: ['release.block_registry.write'],
      corsClass: 'release-worker',
      audience: 'release-worker',
      csrf: 'forbidden',
      rawBodySignature: 'required',
      idempotency: 'required',
      ifMatch: 'none',
      rateClass: 'release-registry-write',
      rateLimit: 20,
      rateWindowSeconds: 60,
      rateScope: 'release',
      requestSchema: 'BlockRegistrationRequestSchema',
      successSchema: 'BlockDefinitionVersionResourceSchema',
      openApiSuccessSchema: 'BlockDefinitionRegistryRecordSchema',
      criticality: 'critical',
      bolaTest:
        'trusted release principal owns the immutable block key/version',
    },
    {
      ...contentSchemaRegistryRouteDefaults,
      method: 'GET',
      path: '/api/v1/cms/content-types',
      operationId: 'CMS-03A-06',
      stepUp: 'none',
      authClass: 'registry_reader',
      capability: 'cms.schema_registry.read',
      capabilities: ['cms.schema_registry.read', 'cms.schema_designer'],
      corsClass: 'cms-console',
      audience: 'browser',
      csrf: 'none',
      rawBodySignature: 'none',
      idempotency: 'none',
      ifMatch: 'none',
      rateClass: 'cms-definition-read',
      rateLimit: 120,
      partyRateLimit: 240,
      rateWindowSeconds: 60,
      rateScope: 'user',
      requestSchema: 'ContentSchemaRegistryListQuerySchema',
      successSchema: 'ContentSchemaRegistryListPageSchema',
      bolaTest: 'caller receives only its authorized registry projection',
    },
    {
      ...contentSchemaRegistryRouteDefaults,
      method: 'GET',
      path: '/api/v1/cms/content-types/{contentTypeId}/versions/{versionId}',
      operationId: 'CMS-03A-07',
      stepUp: 'none',
      authClass: 'registry_reader',
      capability: 'cms.schema_registry.read',
      capabilities: ['cms.schema_registry.read', 'cms.schema_designer'],
      corsClass: 'cms-console',
      audience: 'browser',
      csrf: 'none',
      rawBodySignature: 'none',
      idempotency: 'none',
      ifMatch: 'none',
      rateClass: 'cms-definition-read',
      rateLimit: 120,
      partyRateLimit: 240,
      rateWindowSeconds: 60,
      rateScope: 'user',
      requestSchema: 'ContentSchemaRegistryDetailParamsSchema',
      successSchema: 'ContentSchemaRegistryDetailSchema',
      bolaTest: 'caller receives only its authorized version projection',
    },
    {
      ...contentSchemaRegistryRouteDefaults,
      method: 'POST',
      path: '/api/v1/cms/blocks/versions/{blockDefinitionVersionId}/lifecycle',
      operationId: 'CMS-03A-08',
      stepUp: 'none',
      authClass: 'signed_release_worker',
      capability: 'release.block_registry.write',
      capabilities: ['release.block_registry.write'],
      corsClass: 'release-worker',
      audience: 'release-worker',
      csrf: 'forbidden',
      rawBodySignature: 'required',
      idempotency: 'required',
      ifMatch: 'required',
      rateClass: 'release-registry-lifecycle',
      rateLimit: 20,
      rateWindowSeconds: 60,
      rateScope: 'release',
      requestSchema: 'BlockLifecycleAdvanceRequestSchema',
      successSchema: 'BlockLifecycleEventResourceSchema',
      openApiSuccessSchema: 'BlockLifecycleEventReceiptSchema',
      criticality: 'critical',
      bolaTest:
        'trusted release principal owns the signed lifecycle transition',
    },
    {
      ...contentSchemaRegistryRouteDefaults,
      method: 'POST',
      path: '/api/v1/cms/content-types/{contentTypeId}/versions/{versionId}/successors',
      operationId: 'CMS-03A-09',
      stepUp: 'none',
      authClass: 'schema_designer',
      capability: 'cms.schema_designer',
      capabilities: ['cms.schema_designer'],
      corsClass: 'cms-console',
      audience: 'browser',
      csrf: 'required',
      rawBodySignature: 'none',
      idempotency: 'required',
      ifMatch: 'required',
      rateClass: 'cms-definition-write',
      rateLimit: 30,
      partyRateLimit: 60,
      rateWindowSeconds: 60,
      rateScope: 'user',
      requestSchema: 'SchemaSuccessorRequestSchema',
      successSchema: 'ContentTypeVersionResourceSchema',
      bolaTest: 'caller scope reads the immutable source version',
    },
    {
      ...contentSchemaRegistryRouteDefaults,
      method: 'POST',
      path: '/api/v1/cms/content-types/{contentTypeId}/versions/{versionId}/dry-runs',
      operationId: 'CMS-03A-10',
      stepUp: 'none',
      authClass: 'schema_designer',
      capability: 'cms.schema_designer',
      capabilities: ['cms.schema_designer'],
      corsClass: 'cms-console',
      audience: 'browser',
      csrf: 'required',
      rawBodySignature: 'none',
      idempotency: 'required',
      ifMatch: 'required',
      rateClass: 'cms-definition-write',
      rateLimit: 30,
      partyRateLimit: 60,
      rateWindowSeconds: 60,
      rateScope: 'user',
      requestSchema: 'SchemaDryRunRequestSchema',
      successSchema: 'SchemaDryRunResourceSchema',
      bolaTest: 'caller scope owns the draft candidate version',
    },
    {
      ...contentSchemaRegistryRouteDefaults,
      method: 'POST',
      path: '/api/v1/cms/content-types/{contentTypeId}/versions/{versionId}/reviews',
      operationId: 'CMS-03A-11',
      stepUp: 'none',
      authClass: 'schema_designer',
      capability: 'cms.schema_designer',
      capabilities: ['cms.schema_designer'],
      corsClass: 'cms-console',
      audience: 'browser',
      csrf: 'required',
      rawBodySignature: 'none',
      idempotency: 'required',
      ifMatch: 'required',
      rateClass: 'cms-definition-write',
      rateLimit: 30,
      partyRateLimit: 60,
      rateWindowSeconds: 60,
      rateScope: 'user',
      requestSchema: 'SchemaReviewSubmissionRequestSchema',
      successSchema: 'SchemaReviewResourceSchema',
      bolaTest: 'caller scope owns the draft candidate with a passed dry run',
    },
    {
      ...contentSchemaRegistryRouteDefaults,
      method: 'POST',
      path: '/api/v1/cms/schema-reviews/{reviewId}/decisions',
      operationId: 'CMS-03A-12',
      authClass: 'schema_reviewer',
      capability: 'cms.schema_review',
      capabilities: ['cms.schema_review'],
      corsClass: 'cms-console',
      audience: 'browser',
      csrf: 'required',
      stepUp: 'required',
      rawBodySignature: 'none',
      idempotency: 'required',
      ifMatch: 'required',
      rateClass: 'cms-activation',
      rateLimit: 30,
      partyRateLimit: 60,
      rateWindowSeconds: 60,
      rateScope: 'user',
      requestSchema: 'SchemaReviewDecisionRequestSchema',
      successSchema: 'SchemaReviewDecisionResourceSchema',
      bolaTest: 'assigned reviewer decides only the assigned frozen review',
    },
    {
      ...contentSchemaRegistryRouteDefaults,
      method: 'GET',
      path: '/api/v1/cms/schema-reviews/{reviewId}',
      operationId: 'CMS-03A-13',
      stepUp: 'none',
      authClass: 'review_reader',
      capability: 'cms.schema_designer',
      capabilities: ['cms.schema_designer', 'cms.schema_review'],
      capabilityMode: 'any_of',
      corsClass: 'cms-console',
      audience: 'browser',
      csrf: 'none',
      rawBodySignature: 'none',
      idempotency: 'none',
      ifMatch: 'none',
      rateClass: 'cms-definition-read',
      rateLimit: 120,
      partyRateLimit: 240,
      rateWindowSeconds: 60,
      rateScope: 'user',
      requestSchema: 'SchemaReviewDetailParamsSchema',
      successSchema: 'SchemaReviewResourceSchema',
      bolaTest:
        'submitter, designer, or assigned reviewer reads only its review',
    },
    {
      ...contentSchemaRegistryRouteDefaults,
      method: 'POST',
      path: '/api/v1/cms/schema-reviews/{reviewId}/assignments',
      operationId: 'CMS-03A-14',
      authClass: 'review_assigner',
      capability: 'cms.schema_review.assign',
      capabilities: ['cms.schema_review.assign'],
      corsClass: 'cms-console',
      audience: 'browser',
      csrf: 'required',
      stepUp: 'required',
      rawBodySignature: 'none',
      idempotency: 'required',
      ifMatch: 'required',
      rateClass: 'cms-activation',
      rateLimit: 10,
      partyRateLimit: 20,
      rateWindowSeconds: 60,
      rateScope: 'user',
      requestSchema: 'SchemaReviewAssignmentRequestSchema',
      successSchema: 'SchemaReviewAssignmentResourceSchema',
      bolaTest: 'owner assigns only reviewers on its own frozen review',
    },
    {
      ...contentSchemaRegistryRouteDefaults,
      method: 'POST',
      path: '/api/v1/cms/capability-grants',
      operationId: 'CMS-03A-15',
      authClass: 'cms_owner',
      corsClass: 'cms-console',
      audience: 'browser',
      csrf: 'required',
      stepUp: 'required',
      rawBodySignature: 'none',
      idempotency: 'required',
      ifMatch: 'none',
      rateClass: 'cms-activation',
      rateLimit: 10,
      partyRateLimit: 20,
      rateWindowSeconds: 60,
      rateScope: 'user',
      requestSchema: 'CapabilityGrantRequestSchema',
      successSchema: 'CmsCapabilityGrantResourceSchema',
      bolaTest:
        'receipt-derived owner grants only to existing members of its own organization',
    },
    {
      ...contentSchemaRegistryRouteDefaults,
      method: 'POST',
      path: '/api/v1/cms/capability-grants/{grantId}/renewals',
      operationId: 'CMS-03A-16',
      authClass: 'cms_owner',
      corsClass: 'cms-console',
      audience: 'browser',
      csrf: 'required',
      stepUp: 'required',
      rawBodySignature: 'none',
      idempotency: 'required',
      ifMatch: 'required',
      rateClass: 'cms-activation',
      rateLimit: 10,
      partyRateLimit: 20,
      rateWindowSeconds: 60,
      rateScope: 'user',
      requestSchema: 'CapabilityGrantRenewalRequestSchema',
      successSchema: 'CmsCapabilityGrantResourceSchema',
      bolaTest:
        'receipt-derived owner renews only grants in its own organization',
    },
    {
      ...contentSchemaRegistryRouteDefaults,
      method: 'POST',
      path: '/api/v1/cms/capability-grants/{grantId}/revocations',
      operationId: 'CMS-03A-17',
      authClass: 'cms_owner',
      corsClass: 'cms-console',
      audience: 'browser',
      csrf: 'required',
      stepUp: 'required',
      rawBodySignature: 'none',
      idempotency: 'required',
      ifMatch: 'required',
      rateClass: 'cms-activation',
      rateLimit: 10,
      partyRateLimit: 20,
      rateWindowSeconds: 60,
      rateScope: 'user',
      requestSchema: 'CapabilityGrantRevocationRequestSchema',
      successSchema: 'CmsCapabilityGrantResourceSchema',
      bolaTest:
        'receipt-derived owner revokes only grants in its own organization',
    },
    {
      ...contentSchemaRegistryRouteDefaults,
      method: 'GET',
      path: '/api/v1/cms/capability-grants',
      operationId: 'CMS-03A-18',
      stepUp: 'none',
      authClass: 'cms_owner',
      corsClass: 'cms-console',
      audience: 'browser',
      csrf: 'none',
      rawBodySignature: 'none',
      idempotency: 'none',
      ifMatch: 'none',
      rateClass: 'cms-definition-read',
      rateLimit: 120,
      partyRateLimit: 240,
      rateWindowSeconds: 60,
      rateScope: 'user',
      requestSchema: 'CmsCapabilityGrantListQuerySchema',
      successSchema: 'CmsCapabilityGrantListPageSchema',
      bolaTest:
        'receipt-derived owner lists only grants in its own organization',
    },
    {
      ...editorialRouteDefaults,
      method: 'POST',
      path: '/api/v1/cms/entries/{entryId}/revisions',
      operationId: 'CMS-03B-01',
      authClass: 'editorial_author',
      capabilities: ['cms.author', 'cms.editor'],
      capabilityMode: 'any_of',
      corsClass: 'cms-console',
      audience: 'browser',
      csrf: 'required',
      rawBodySignature: 'none',
      idempotency: 'required',
      ifMatch: 'required',
      rateClass: 'cms-entry-write',
      rateLimit: 120,
      partyRateLimit: 240,
      rateWindowSeconds: 60,
      rateScope: 'user',
      timeoutMs: 15_000,
      sloTier: 'tier_2',
      requestSchema: 'EntryRevisionApiRequestSchema',
      successSchema: 'EntryRevisionResourceSchema',
      bolaTest: 'caller may revise only its assigned readable entry',
    },
    {
      ...editorialRouteDefaults,
      method: 'POST',
      path: '/api/v1/cms/entries/{entryId}/conflicts/{conflictId}/resolve',
      operationId: 'CMS-03B-02',
      authClass: 'editorial_author',
      capabilities: ['cms.author', 'cms.editor'],
      capabilityMode: 'any_of',
      corsClass: 'cms-console',
      audience: 'browser',
      csrf: 'required',
      rawBodySignature: 'none',
      idempotency: 'required',
      ifMatch: 'required',
      rateClass: 'cms-entry-conflict',
      rateLimit: 60,
      partyRateLimit: 120,
      rateWindowSeconds: 60,
      rateScope: 'user',
      timeoutMs: 15_000,
      sloTier: 'tier_2',
      requestSchema: 'ConflictResolutionApiRequestSchema',
      successSchema: 'EntryRevisionResourceSchema',
      bolaTest:
        'caller may resolve only the open conflict on its assigned entry',
    },
    {
      ...editorialRouteDefaults,
      method: 'GET',
      path: '/api/v1/cms/entries/{entryId}/revisions',
      operationId: 'CMS-03B-03',
      authClass: 'editorial_reader',
      capabilities: ['cms.author', 'cms.editor', 'cms.reviewer'],
      capabilityMode: 'any_of',
      corsClass: 'cms-console',
      audience: 'browser',
      csrf: 'none',
      rawBodySignature: 'none',
      idempotency: 'none',
      ifMatch: 'none',
      rateClass: 'cms-entry-read',
      rateLimit: 300,
      partyRateLimit: 600,
      rateWindowSeconds: 60,
      rateScope: 'user',
      timeoutMs: 8_000,
      sloTier: 'tier_1',
      requestSchema: 'RevisionHistoryApiRequestSchema',
      successSchema: 'RevisionHistoryPageSchema',
      bolaTest: 'caller reads only revisions of its authorized entry',
    },
    {
      ...editorialRouteDefaults,
      method: 'POST',
      path: '/api/v1/cms/entries/{entryId}/revisions/{revisionId}/restore',
      operationId: 'CMS-03B-04',
      authClass: 'editorial_author',
      capabilities: ['cms.author', 'cms.editor'],
      capabilityMode: 'any_of',
      corsClass: 'cms-console',
      audience: 'browser',
      csrf: 'required',
      rawBodySignature: 'none',
      idempotency: 'required',
      ifMatch: 'required',
      rateClass: 'cms-entry-write',
      rateLimit: 30,
      partyRateLimit: 60,
      rateWindowSeconds: 60,
      rateScope: 'user',
      timeoutMs: 15_000,
      sloTier: 'tier_2',
      requestSchema: 'RevisionRestoreApiRequestSchema',
      successSchema: 'EntryRevisionResourceSchema',
      bolaTest:
        'caller may restore only a readable revision of its assigned entry',
    },
    {
      ...editorialRouteDefaults,
      method: 'POST',
      path: '/api/v1/cms/entries',
      operationId: 'CMS-03B-10',
      authClass: 'editorial_author',
      capabilities: ['cms.author', 'cms.editor'],
      capabilityMode: 'any_of',
      corsClass: 'cms-console',
      audience: 'browser',
      csrf: 'required',
      rawBodySignature: 'none',
      idempotency: 'required',
      ifMatch: 'none',
      rateClass: 'cms-entry-write',
      rateLimit: 120,
      partyRateLimit: 240,
      rateWindowSeconds: 60,
      rateScope: 'user',
      timeoutMs: 15_000,
      sloTier: 'tier_2',
      requestSchema: 'EntryCreateApiRequestSchema',
      successSchema: 'EntryCreateResourceSchema',
      bolaTest: 'caller may create only within its authorized CMS owner scope',
    },
    {
      ...editorialRouteDefaults,
      method: 'GET',
      path: '/api/v1/cms/entries/{entryId}',
      operationId: 'CMS-03B-11',
      authClass: 'editorial_reader',
      capabilities: ['cms.author', 'cms.editor'],
      capabilityMode: 'any_of',
      corsClass: 'cms-console',
      audience: 'browser',
      csrf: 'none',
      rawBodySignature: 'none',
      idempotency: 'none',
      ifMatch: 'none',
      rateClass: 'cms-entry-read',
      rateLimit: 300,
      partyRateLimit: 600,
      rateWindowSeconds: 60,
      rateScope: 'user',
      timeoutMs: 8_000,
      sloTier: 'tier_1',
      requestSchema: 'EntryDraftDetailApiRequestSchema',
      successSchema: 'EntryDraftDetailResourceSchema',
      bolaTest: 'caller reads only its authorized current draft projection',
    },
    {
      ...contentSchemaRegistryRouteDefaults,
      method: 'GET',
      path: '/api/v1/cms/templates/context',
      operationId: 'cmsTemplateContextRead',
      authClass: 'template_designer',
      capability: 'cms.template_designer',
      capabilities: ['cms.template_designer'],
      corsClass: 'cms-console',
      audience: 'browser',
      csrf: 'none',
      rawBodySignature: 'none',
      idempotency: 'none',
      ifMatch: 'none',
      rateClass: 'cms-template-read',
      rateLimit: 60,
      partyRateLimit: 60,
      rateWindowSeconds: 60,
      rateScope: 'user',
      requestSchema: 'EmptyRequestSchema',
      successSchema: 'TemplateDesignerContextSchema',
      bolaTest:
        'caller sees only owned active type and supported block selectors',
    },
    {
      ...contentSchemaRegistryRouteDefaults,
      method: 'POST',
      path: '/api/v1/cms/templates/versions',
      operationId: 'CMS-03C-01',
      authClass: 'template_designer',
      capability: 'cms.template_designer',
      capabilities: ['cms.template_designer'],
      corsClass: 'cms-console',
      audience: 'browser',
      csrf: 'required',
      rawBodySignature: 'none',
      idempotency: 'required',
      ifMatch: 'conditional',
      rateClass: 'cms-template-write',
      rateLimit: 30,
      partyRateLimit: 60,
      rateWindowSeconds: 60,
      rateScope: 'user',
      requestSchema: 'TemplateVersionApiRequestSchema',
      successSchema: 'TemplateVersionResourceSchema',
      bolaTest: 'caller owns the target template scope and version',
    },
    {
      ...editorialRouteDefaults,
      method: 'POST',
      path: '/api/v1/cms/compositions/pattern-instances',
      operationId: 'CMS-03C-02',
      authClass: 'editorial_author',
      capabilities: ['cms.author', 'cms.editor'],
      capabilityMode: 'any_of',
      corsClass: 'cms-console',
      audience: 'browser',
      csrf: 'required',
      rawBodySignature: 'none',
      idempotency: 'required',
      ifMatch: 'required',
      rateClass: 'cms-composition-write',
      rateLimit: 120,
      partyRateLimit: 240,
      rateWindowSeconds: 60,
      rateScope: 'user',
      timeoutMs: 15_000,
      sloTier: 'tier_2',
      requestSchema: 'PatternInstanceApiRequestSchema',
      successSchema: 'CompositionInstanceResourceSchema',
      bolaTest: 'caller may edit the assigned draft and read the exact pattern',
    },
    {
      ...contentSchemaRegistryRouteDefaults,
      method: 'POST',
      path: '/api/v1/cms/taxonomies/{taxonomyId}/terms/actions',
      operationId: 'CMS-03C-03',
      authClass: 'taxonomy_curator',
      capability: 'cms.taxonomy_curator',
      capabilities: ['cms.taxonomy_curator'],
      corsClass: 'cms-console',
      audience: 'browser',
      csrf: 'required',
      rawBodySignature: 'none',
      idempotency: 'required',
      ifMatch: 'required',
      rateClass: 'cms-taxonomy-write',
      rateLimit: 60,
      partyRateLimit: 120,
      rateWindowSeconds: 60,
      rateScope: 'user',
      timeoutMs: 15_000,
      sloTier: 'tier_2',
      requestSchema: 'TaxonomyTermActionApiRequestSchema',
      successSchema: 'TaxonomyTermResourceSchema',
      bolaTest: 'caller may curate only an authorized taxonomy and term',
    },
    {
      ...contentSchemaRegistryRouteDefaults,
      method: 'GET',
      path: '/api/v1/cms/templates/{templateKey}',
      operationId: 'cmsTemplateLatestRead',
      authClass: 'template_designer',
      capability: 'cms.template_designer',
      capabilities: ['cms.template_designer'],
      corsClass: 'cms-console',
      audience: 'browser',
      csrf: 'none',
      rawBodySignature: 'none',
      idempotency: 'none',
      ifMatch: 'none',
      rateClass: 'cms-template-read',
      rateLimit: 60,
      partyRateLimit: 60,
      rateWindowSeconds: 60,
      rateScope: 'user',
      requestSchema: 'TemplateLatestApiRequestSchema',
      successSchema: 'TemplateVersionDetailSchema',
      bolaTest: 'caller reads only its owned latest template definition',
    },
    {
      ...editorialRouteDefaults,
      method: 'POST',
      path: '/api/v1/cms/entries/{entryId}/locales/{locale}/variants',
      operationId: 'CMS-03C-04',
      authClass: 'editorial_author',
      capabilities: ['cms.author', 'cms.editor'],
      capabilityMode: 'any_of',
      corsClass: 'cms-console',
      audience: 'browser',
      csrf: 'required',
      rawBodySignature: 'none',
      idempotency: 'required',
      ifMatch: 'required',
      rateClass: 'cms-locale-write',
      rateLimit: 60,
      partyRateLimit: 120,
      rateWindowSeconds: 60,
      rateScope: 'user',
      timeoutMs: 15_000,
      sloTier: 'tier_2',
      requestSchema: 'LocaleVariantApiRequestSchema',
      successSchema: 'LocaleVariantResourceSchema',
      bolaTest:
        'caller may translate only its authorized source revision and locale',
    },
    {
      ...editorialRouteDefaults,
      method: 'POST',
      path: '/api/v1/cms/entries/{entryId}/related-content',
      operationId: 'CMS-03C-05',
      authClass: 'editorial_author',
      capabilities: ['cms.author', 'cms.editor'],
      capabilityMode: 'any_of',
      corsClass: 'cms-console',
      audience: 'browser',
      csrf: 'required',
      rawBodySignature: 'none',
      idempotency: 'required',
      ifMatch: 'required',
      rateClass: 'cms-related-content-write',
      rateLimit: 60,
      partyRateLimit: 120,
      rateWindowSeconds: 60,
      rateScope: 'user',
      timeoutMs: 15_000,
      sloTier: 'tier_2',
      requestSchema: 'RelatedContentApiRequestSchema',
      successSchema: 'RelatedContentResourceSchema',
      bolaTest:
        'caller may curate related targets only within its authorized source entry',
    },
    {
      ...identityStepUpRouteDefaults,
      method: 'POST',
      path: '/api/v1/admin/identity/mfa-factor-resets',
      operationId: 'CFG-05B-06',
      authClass: 'admin_step_up',
      capability: 'admin.identity.mfa_reset',
      capabilities: ['admin.identity.mfa_reset'],
      audience: 'browser',
      csrf: 'required',
      stepUp: 'required',
      rawBodySignature: 'none',
      idempotency: 'required',
      ifMatch: 'none',
      cacheControl: 'no-store',
      rateClass: 'admin_mfa_factor_reset',
      rateLimit: 5,
      partyRateLimit: 10,
      rateWindowSeconds: 3_600,
      rateScope: 'user',
      timeoutMs: 15_000,
      sloTier: 'tier_2',
      criticality: 'critical',
      requestSchema: 'Cfg05b06MfaFactorResetRequestSchema',
      successSchema: 'Cfg05b06MfaFactorResetResponseSchema',
      bolaTest:
        'operator resets only a confirmed member of its capability organization, never itself',
    },
    {
      ...identityReadRouteDefaults,
      method: 'GET',
      path: '/api/v1/admin/capability-snapshot',
      operationId: 'CFG-05B-07',
      owner: 'Identity',
      audience: 'browser',
      csrf: 'none',
      rawBodySignature: 'none',
      idempotency: 'none',
      ifMatch: 'none',
      cacheControl: 'no-store',
      rateClass: 'admin_capability_snapshot_read',
      rateLimit: 120,
      rateWindowSeconds: 60,
      rateScope: 'user',
      timeoutMs: 8_000,
      sloTier: 'tier_1',
      criticality: 'high',
      requestSchema: 'EmptyRequestSchema',
      successSchema: 'Cfg05b07CapabilitySnapshotResponseSchema',
      bolaTest:
        'caller receives only the named admin capabilities of its own verified session and acting party',
    },
  ],
  consumers: [
    {
      consumerId: 'platform.job.execute',
      owner: 'Infrastructure',
      messageSchema: 'QueueEnvelopeSchema',
      queueName: 'platform-jobs',
      leaseSeconds: 300,
      heartbeatSeconds: 60,
      maxLeaseSeconds: 840,
      maxDeliveries: 4,
      retryClass: 'bounded_exponential',
      retryDelaysSeconds: [15, 60, 300],
      deadLetterClass: 'platform-jobs-dlq',
      acceptedEvents: [
        { eventType: 'job.requested', schemaVersion: 1 },
        { eventType: 'identity.facet.changed.v1', schemaVersion: 1 },
        { eventType: 'identity.alias.changed.v1', schemaVersion: 1 },
        {
          eventType: 'identity.acting-context.revoked.v1',
          schemaVersion: 1,
        },
        { eventType: 'identity.organization.changed.v1', schemaVersion: 1 },
        { eventType: 'identity.relationship.changed.v1', schemaVersion: 1 },
        { eventType: 'identity.governance.activated.v1', schemaVersion: 1 },
      ],
      sloTier: 'tier_1',
      runbook: 'docs/runbooks/platform/jobs-outbox-reconciliation.md',
    },
    {
      consumerId: 'profile.match',
      owner: 'Profiles',
      messageSchema: 'ProfileQueueEnvelopeSchema',
      queueName: 'profile-match',
      leaseSeconds: 300,
      heartbeatSeconds: 60,
      maxLeaseSeconds: 840,
      maxDeliveries: 4,
      retryClass: 'bounded_exponential',
      retryDelaysSeconds: [15, 60, 300],
      deadLetterClass: 'profile-match-dlq',
      acceptedEvents: [
        { eventType: 'profile.shadow.created.v1', schemaVersion: 1 },
      ],
      sloTier: 'tier_2',
      runbook: 'docs/runbooks/platform/jobs-outbox-reconciliation.md',
    },
    {
      consumerId: 'profile.invitation',
      owner: 'Profiles',
      messageSchema: 'ProfileQueueEnvelopeSchema',
      queueName: 'profile-invitation',
      leaseSeconds: 300,
      heartbeatSeconds: 60,
      maxLeaseSeconds: 840,
      maxDeliveries: 4,
      retryClass: 'bounded_exponential',
      retryDelaysSeconds: [15, 60, 300],
      deadLetterClass: 'profile-invitation-dlq',
      acceptedEvents: [
        { eventType: 'profile.shadow.created.v1', schemaVersion: 1 },
      ],
      sloTier: 'tier_2',
      runbook: 'docs/runbooks/platform/jobs-outbox-reconciliation.md',
    },
    {
      consumerId: 'profile.claim-deadline',
      owner: 'Profiles',
      messageSchema: 'ProfileQueueEnvelopeSchema',
      queueName: 'profile-claim-deadline',
      leaseSeconds: 300,
      heartbeatSeconds: 60,
      maxLeaseSeconds: 840,
      maxDeliveries: 4,
      retryClass: 'bounded_exponential',
      retryDelaysSeconds: [15, 60, 300],
      deadLetterClass: 'profile-claim-deadline-dlq',
      acceptedEvents: [
        { eventType: 'profile.claim.changed.v1', schemaVersion: 1 },
      ],
      sloTier: 'tier_2',
      runbook: 'docs/runbooks/platform/jobs-outbox-reconciliation.md',
    },
    {
      consumerId: 'profile.proof-reconcile',
      owner: 'Profiles',
      messageSchema: 'ProfileQueueEnvelopeSchema',
      queueName: 'profile-proof-reconcile',
      leaseSeconds: 300,
      heartbeatSeconds: 60,
      maxLeaseSeconds: 840,
      maxDeliveries: 4,
      retryClass: 'bounded_exponential',
      retryDelaysSeconds: [15, 60, 300],
      deadLetterClass: 'profile-proof-reconcile-dlq',
      acceptedEvents: [
        { eventType: 'profile.claim.changed.v1', schemaVersion: 1 },
      ],
      sloTier: 'tier_2',
      runbook: 'docs/runbooks/platform/jobs-outbox-reconciliation.md',
    },
  ],
  providers: [],
  retention: [
    {
      dataClass: 'operational.events',
      owner: 'Infrastructure',
      retentionDays: 30,
      deletionMode: 'hard_delete',
      legalHoldSupported: false,
      runbook: 'docs/runbooks/platform/retention.md',
    },
  ],
  slos: [
    {
      tier: 'tier_1',
      owner: 'Infrastructure',
      targetBasisPoints: 9_990,
      measurementLabel: 'api.availability',
      alertRoute: 'platform.on_call',
      runbook: 'docs/runbooks/platform/slo.md',
    },
    {
      tier: 'tier_2',
      owner: 'Infrastructure',
      targetBasisPoints: 9_990,
      measurementLabel: 'api.availability',
      alertRoute: 'platform.on_call',
      runbook: 'docs/runbooks/platform/slo.md',
    },
  ],
});
