/** Declared request fields per Slice 09 operation (explicit, not inferred). */
import type { contentSchemaRegistryRoutePolicies } from '../../packages/contracts/src/content-schema-registry';

export type OperationId =
  (typeof contentSchemaRegistryRoutePolicies)[number]['operationId'];

export const operationIds: readonly OperationId[] = [
  'CMS-03A-01',
  'CMS-03A-02',
  'CMS-03A-03',
  'CMS-03A-04',
  'CMS-03A-05',
  'CMS-03A-06',
  'CMS-03A-07',
  'CMS-03A-08',
  'CMS-03A-09',
  'CMS-03A-10',
  'CMS-03A-11',
  'CMS-03A-12',
  'CMS-03A-13',
  'CMS-03A-14',
  'CMS-03A-15',
  'CMS-03A-16',
  'CMS-03A-17',
  'CMS-03A-18',
];

export const declaredRequestFields: Readonly<
  Record<OperationId, readonly string[]>
> = {
  'CMS-03A-01': [
    'typeKey',
    'label',
    'ownerCapability',
    'sourceLocale',
    'defaultLocale',
    'workflowKey',
    'workflowVersion',
    'defaultTemplateVersionId',
    'fields',
    'relations',
    'templateBindings',
    'capabilityBindings',
  ],
  'CMS-03A-02': [
    'stableFieldId',
    'key',
    'kind',
    'constraints',
    'required',
    'validatorKey',
    'validatorVersion',
    'defaultMode',
    'defaultValue',
    'localizationMode',
    'editorConfig',
    'lifecycle',
    'migrationPlanId',
  ],
  'CMS-03A-03': [
    'fieldId',
    'targetKind',
    'targetType',
    'projectionKey',
    'cardinality',
    'min',
    'max',
    'ordered',
    'onUnavailable',
  ],
  'CMS-03A-04': [
    'expectedVersion',
    'dryRunId',
    'approvalIds',
    'expectedActivationEvidenceHash',
    'migrationPlanId',
  ],
  'CMS-03A-05': [
    'blockKey',
    'blockVersion',
    'propsSchemaRef',
    'propsSchemaHash',
    'propsSchemaSnapshot',
    'propsSnapshotHash',
    'propsSnapshotAttestation',
    'rendererRef',
    'allowedChildren',
    'slotRules',
    'dataSourcePermissions',
    'accessibility',
    'compatibility',
    'lifecycle',
    'releaseDigest',
  ],
  'CMS-03A-06': [
    'resourceKind',
    'keyPrefix',
    'lifecycle',
    'state',
    'limit',
    'cursor',
    'sort',
    'direction',
  ],
  'CMS-03A-07': ['contentTypeId', 'versionId'],
  'CMS-03A-08': [
    'fromLifecycle',
    'toLifecycle',
    'expectedVersion',
    'releaseDigest',
  ],
  'CMS-03A-09': ['expectedVersion'],
  'CMS-03A-10': ['expectedVersion', 'transformKey', 'transformVersion'],
  'CMS-03A-11': ['expectedVersion', 'dryRunId'],
  'CMS-03A-12': ['expectedVersion', 'decision'],
  'CMS-03A-13': ['reviewId'],
  // The create variant of the discriminated assignment union; the revoke
  // variant is proven separately.
  'CMS-03A-14': [
    'action',
    'expectedVersion',
    'reviewerPersonId',
    'expiresAt',
    'reason',
  ],
  'CMS-03A-15': ['subjectPersonId', 'capability', 'validThrough', 'reason'],
  'CMS-03A-16': ['expectedVersion', 'validThrough', 'reason'],
  'CMS-03A-17': ['expectedVersion', 'reason'],
  'CMS-03A-18': [
    'subjectPersonId',
    'capability',
    'state',
    'limit',
    'cursor',
    'sort',
    'direction',
  ],
};
export const optionalRequestFields: Readonly<
  Record<OperationId, readonly string[]>
> = {
  'CMS-03A-01': ['defaultTemplateVersionId'],
  'CMS-03A-02': ['stableFieldId', 'defaultValue'],
  'CMS-03A-03': [],
  'CMS-03A-04': ['expectedActivationEvidenceHash'],
  'CMS-03A-05': [],
  'CMS-03A-06': [
    'resourceKind',
    'keyPrefix',
    'lifecycle',
    'state',
    'limit',
    'cursor',
    'sort',
    'direction',
  ],
  'CMS-03A-07': [],
  'CMS-03A-08': [],
  'CMS-03A-09': [],
  'CMS-03A-10': [],
  'CMS-03A-11': [],
  'CMS-03A-12': [],
  'CMS-03A-13': [],
  'CMS-03A-14': ['reason'],
  'CMS-03A-15': ['reason'],
  'CMS-03A-16': ['reason'],
  'CMS-03A-17': ['reason'],
  'CMS-03A-18': [
    'subjectPersonId',
    'capability',
    'state',
    'limit',
    'cursor',
    'sort',
    'direction',
  ],
};

export const requiredFields = (operationId: OperationId): readonly string[] =>
  declaredRequestFields[operationId].filter(
    (fieldName) => !optionalRequestFields[operationId].includes(fieldName),
  );
