/*
 * BE03b "Time authority (E8)" and DEC-153: schedule times are resolved over ONE
 * pinned snapshot of the IANA tz database. The snapshot is a content-addressed
 * build asset (`tzdb-snapshot-data.ts`) generated by `infra/generate-tzdb-snapshot.mjs`
 * from the two IANA release tarballs named below. The release tag is the code
 * constant `CMS_TZDB_VERSION`; the SHA-256 of the exact snapshot text is
 * `CMS_TZDB_SHA256`, verified at module load (a mismatch answers every schedule
 * command 503 `DEPENDENCY_UNAVAILABLE`). `platform_private.cms_tzdb_version()`
 * must return the same tag (a CI parity test compares the two). Advancing the
 * pin is code plus a forward migration; a stored schedule keeps the tag and the
 * instant it was accepted with, so a later pin never alters an existing instant.
 */

/** The pinned IANA release tag (`^[A-Za-z0-9._-]{1,32}$`). */
export const CMS_TZDB_VERSION = '2026e';

/** SHA-256 (lowercase hex) of the exact snapshot text `CMS_TZDB_SNAPSHOT_JSON`. */
export const CMS_TZDB_SHA256 =
  '862c1656e10ab81c18359393473448dcd2540d4254fa5b2c432a2989cac81c3b';

/**
 * The IANA release the snapshot is generated from: the two tarballs, pinned by
 * their SHA-256, and the command that regenerates the snapshot. DEC-153 records
 * the same values.
 */
export const CMS_TZDB_SOURCE = {
  release: '2026e',
  releasedAt: '2026-09-29',
  tzdataUrl: 'https://data.iana.org/time-zones/releases/tzdata2026e.tar.gz',
  tzdataSha256:
    'b26882805f26aac59d5b222978e6580484b834ccdc98be89df2f05a6dc53a652',
  tzcodeUrl: 'https://data.iana.org/time-zones/releases/tzcode2026e.tar.gz',
  tzcodeSha256:
    'cc3d27ca2a0d8399504551b920970d80af83bfb9c216e8082a15491921935d54',
  generationCommand: 'node infra/generate-tzdb-snapshot.mjs --download',
} as const;
