import { z } from 'zod';

/*
 * The reduced IANA tz snapshot (`cms.tzdb.v1`) generated by
 * `infra/generate-tzdb-snapshot.mjs`: zone names map to zone indexes (several
 * names share one zone), and a zone is
 * `[distinct UT offsets, initial offset index, transition deltas, offset index per
 * transition, POSIX footer]`. Time resolution needs nothing else.
 */

export const TZDB_SNAPSHOT_FORMAT = 'cms.tzdb.v1' as const;

const ZoneSchema = z
  .tuple([
    z.array(z.number().int().min(-86_400).max(86_400)).min(1).max(64),
    z.number().int().min(0),
    // The first delta is the absolute first transition (it may precede 1970); later ones ascend.
    z.array(z.number().int()),
    z.array(z.number().int().min(0)),
    z.string().max(128),
  ])
  .superRefine(([offsets, initial, deltas, indexes], context) => {
    if (initial >= offsets.length)
      context.addIssue({
        code: 'custom',
        message: 'initial offset index is out of range',
      });
    if (deltas.length !== indexes.length)
      context.addIssue({
        code: 'custom',
        message: 'one offset index per transition delta',
      });
    if (deltas.slice(1).some((delta) => delta <= 0))
      context.addIssue({
        code: 'custom',
        message: 'transitions ascend strictly',
      });
    if (indexes.some((index) => index >= offsets.length))
      context.addIssue({
        code: 'custom',
        message: 'transition offset index is out of range',
      });
  });

export const TzdbSnapshotSchema = z
  .strictObject({
    format: z.literal(TZDB_SNAPSHOT_FORMAT),
    release: z.string().regex(/^[A-Za-z0-9._-]{1,32}$/u),
    names: z.record(z.string().min(1).max(64), z.number().int().min(0)),
    zones: z.array(ZoneSchema).min(1),
  })
  .superRefine((snapshot, context) => {
    for (const [name, index] of Object.entries(snapshot.names))
      if (index >= snapshot.zones.length)
        context.addIssue({
          code: 'custom',
          path: ['names', name],
          message: 'zone name points past the zone table',
        });
  });

export type TzdbSnapshot = z.infer<typeof TzdbSnapshotSchema>;

/** Parses snapshot text, throwing a descriptive error for anything malformed. */
export const parseSnapshot = (text: string): TzdbSnapshot => {
  let value: unknown;
  try {
    value = JSON.parse(text);
  } catch {
    throw new Error('The tz snapshot is not valid JSON.');
  }
  const parsed = TzdbSnapshotSchema.safeParse(value);
  if (!parsed.success) throw new Error('The tz snapshot is malformed.');
  return parsed.data;
};

/** Lowercase SHA-256 hex of the UTF-8 bytes of `text` (Web Crypto: Worker, browser, Node). */
export const sha256Hex = async (text: string): Promise<string> => {
  const digest = await globalThis.crypto.subtle.digest(
    'SHA-256',
    new TextEncoder().encode(text),
  );
  return Array.from(new Uint8Array(digest), (byte) =>
    byte.toString(16).padStart(2, '0'),
  ).join('');
};
