import type { ContentSchemaRegistryRoutePolicy } from './route-policy.ts';
import {
  humanMutationErrors,
  humanStepUpMutationErrors,
  tier2Slo,
} from './routes-errors.ts';

const humanMutationDefaults = {
  method: 'POST',
  auth: 'schema_designer',
  capability: 'cms.schema_designer',
  cors: 'cms-console',
  csrf: 'required',
  stepUp: 'none',
  rawBodySignature: 'none',
  idempotency: 'required',
  rateWindowSeconds: 60,
  rateScope: 'user',
  timeoutMs: 15_000,
  cacheControl: 'no-store',
  slo: tier2Slo,
  audience: 'browser',
  errors: humanMutationErrors,
} as const;

export const humanRoutePolicies = [
  {
    ...humanMutationDefaults,
    operationId: 'CMS-03A-01',
    path: '/api/v1/cms/content-types',
    requestSchema: 'ContentTypeDraftRequestSchema',
    successSchema: 'ContentTypeVersionResourceSchema',
    successStatus: 201,
    ifMatch: 'none',
    rateClass: 'cms-definition-write',
    rateLimit: 30,
    partyRateLimit: 60,
  },
  {
    ...humanMutationDefaults,
    operationId: 'CMS-03A-02',
    path: '/api/v1/cms/content-types/{contentTypeId}/versions/{versionId}/fields',
    requestSchema: 'FieldSchemaChangeRequestSchema',
    successSchema: 'FieldDefinitionVersionResourceSchema',
    successStatus: 201,
    ifMatch: 'required',
    rateClass: 'cms-definition-write',
    rateLimit: 60,
    partyRateLimit: 120,
  },
  {
    ...humanMutationDefaults,
    operationId: 'CMS-03A-03',
    path: '/api/v1/cms/content-types/{contentTypeId}/versions/{versionId}/relations',
    requestSchema: 'RelationBindingRequestSchema',
    successSchema: 'RelationDefinitionResourceSchema',
    successStatus: 201,
    ifMatch: 'required',
    rateClass: 'cms-definition-write',
    rateLimit: 60,
    partyRateLimit: 120,
  },
  {
    ...humanMutationDefaults,
    operationId: 'CMS-03A-04',
    path: '/api/v1/cms/content-types/{contentTypeId}/versions/{versionId}/activate',
    requestSchema: 'SchemaActivationRequestSchema',
    successSchema: 'SchemaActivationResourceSchema',
    successStatus: 202,
    successStatuses: [200, 202],
    stepUp: 'required',
    errors: humanStepUpMutationErrors,
    ifMatch: 'required',
    rateClass: 'cms-activation',
    rateLimit: 10,
    partyRateLimit: 20,
  },
] as const satisfies readonly ContentSchemaRegistryRoutePolicy[];
