import type { ContentSchemaRegistryRoutePolicy } from './route-policy.ts';
import {
  humanMutationErrors,
  humanStepUpMutationErrors,
  reviewDetailErrors,
  tier2Slo,
} from './routes-errors.ts';

const browserDefaults = {
  audience: 'browser',
  cors: 'cms-console',
  rawBodySignature: 'none',
  rateWindowSeconds: 60,
  rateScope: 'user',
  timeoutMs: 15_000,
  cacheControl: 'no-store',
  slo: tier2Slo,
} as const;

const designerWriteDefaults = {
  ...browserDefaults,
  method: 'POST',
  auth: 'schema_designer',
  capability: 'cms.schema_designer',
  csrf: 'required',
  stepUp: 'none',
  idempotency: 'required',
  ifMatch: 'required',
  rateClass: 'cms-definition-write',
  rateLimit: 30,
  partyRateLimit: 60,
  errors: humanMutationErrors,
} as const;

const versionPath =
  '/api/v1/cms/content-types/{contentTypeId}/versions/{versionId}';

/** CMS-03A-09 through CMS-03A-14, per the BE03a Route Registry. */
export const reviewRoutePolicies = [
  {
    ...designerWriteDefaults,
    operationId: 'CMS-03A-09',
    path: `${versionPath}/successors`,
    requestSchema: 'SchemaSuccessorRequestSchema',
    successSchema: 'ContentTypeVersionResourceSchema',
    successStatus: 201,
  },
  {
    ...designerWriteDefaults,
    operationId: 'CMS-03A-10',
    path: `${versionPath}/dry-runs`,
    requestSchema: 'SchemaDryRunRequestSchema',
    successSchema: 'SchemaDryRunResourceSchema',
    successStatus: 202,
  },
  {
    ...designerWriteDefaults,
    operationId: 'CMS-03A-11',
    path: `${versionPath}/reviews`,
    requestSchema: 'SchemaReviewSubmissionRequestSchema',
    successSchema: 'SchemaReviewResourceSchema',
    successStatus: 201,
  },
  {
    ...browserDefaults,
    operationId: 'CMS-03A-12',
    method: 'POST',
    path: '/api/v1/cms/schema-reviews/{reviewId}/decisions',
    requestSchema: 'SchemaReviewDecisionRequestSchema',
    successSchema: 'SchemaReviewDecisionResourceSchema',
    successStatus: 201,
    auth: 'schema_reviewer',
    capability: 'cms.schema_review',
    csrf: 'required',
    stepUp: 'required',
    idempotency: 'required',
    ifMatch: 'required',
    rateClass: 'cms-activation',
    rateLimit: 30,
    partyRateLimit: 60,
    errors: humanStepUpMutationErrors,
  },
  {
    ...browserDefaults,
    operationId: 'CMS-03A-13',
    method: 'GET',
    path: '/api/v1/cms/schema-reviews/{reviewId}',
    requestSchema: 'SchemaReviewDetailParamsSchema',
    successSchema: 'SchemaReviewResourceSchema',
    successStatus: 200,
    auth: 'review_reader',
    capability: 'cms.schema_designer',
    capabilities: ['cms.schema_designer', 'cms.schema_review'],
    capabilityMode: 'any_of',
    csrf: 'none',
    stepUp: 'none',
    idempotency: 'none',
    ifMatch: 'none',
    rateClass: 'cms-definition-read',
    rateLimit: 120,
    partyRateLimit: 240,
    errors: reviewDetailErrors,
  },
  {
    ...browserDefaults,
    operationId: 'CMS-03A-14',
    method: 'POST',
    path: '/api/v1/cms/schema-reviews/{reviewId}/assignments',
    requestSchema: 'SchemaReviewAssignmentRequestSchema',
    successSchema: 'SchemaReviewAssignmentResourceSchema',
    successStatus: 201,
    successStatuses: [200, 201],
    auth: 'review_assigner',
    capability: 'cms.schema_review.assign',
    csrf: 'required',
    stepUp: 'required',
    idempotency: 'required',
    ifMatch: 'required',
    rateClass: 'cms-activation',
    rateLimit: 10,
    partyRateLimit: 20,
    errors: humanStepUpMutationErrors,
  },
] as const satisfies readonly ContentSchemaRegistryRoutePolicy[];
