-- Slice 11 shared helper (lane S11-3s, BE03b "Time authority (E8)", DEC-153;
-- tracker P2-S11-AC-103, AC-105): the SQL mirror of the pinned tz release tag.
--
-- CMS_TZDB_VERSION = 2026e is the newest stable IANA release available when lane
-- S11-1 pinned it (2026-10-08; tzdata2026e.tar.gz, snapshot SHA-256
-- 862c1656e10ab81c18359393473448dcd2540d4254fa5b2c432a2989cac81c3b, recorded as raw
-- decision dec-153-pin, generated by `node infra/generate-tzdb-snapshot.mjs --download`).
-- cms_tzdb_version() returns that tag; the schedule RPC re-checks a request's
-- tzdbVersion against it (a mismatch is 422 tzdb_version_mismatch) while the Worker
-- owns the zone rules.  PARITY: the literal below must equal CMS_TZDB_VERSION in
-- packages/contracts/src/cms-editorial/time-authority/tzdb-pin.ts; advancing the pin
-- is code plus a forward migration that redefines this function, and stored schedules
-- keep the tag they were accepted with.  Private; IMMUTABLE.  Forward-only.
begin;

create or replace function platform_private.cms_tzdb_version()
returns text
language sql
immutable
security definer
set search_path = ''
as $body$
  select '2026e'::text
$body$;

comment on function platform_private.cms_tzdb_version() is
  'BE03b E8: the pinned IANA tz release tag, mirroring the TypeScript constant CMS_TZDB_VERSION (DEC-153: 2026e). Private; IMMUTABLE.';

grant create on schema platform_private to wejammin_cms_definer;
alter function platform_private.cms_tzdb_version() owner to wejammin_cms_definer;
revoke create on schema platform_private from wejammin_cms_definer;
revoke all on function platform_private.cms_tzdb_version() from public, anon, authenticated, service_role;

commit;
